### ISSUE TITLE
Find or generate datapackage.json

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#10]
When publisher runs the command for publishing (pushing) data, we need to check if there is a descriptor. If there is then we just pass it, if not we need to generate datapackage.json for it.

## Acceptance criteria

* [x] function (in `/lib/`) for checking `datapackage.json` file in current directory
* [ ] function (in `/lib/`) for generating `datapackage.json` file with minimal required fields
* [ ] function that reads directory and looks up for data files and generates dp based on that

## Tasks

* [x] function that checks if `dp.json` exists
* [ ] function that looks up for data files and generates dp based on `csv, tsv, json, geojson, topojson etc.` files in current (and child `/data/`) directories
* [x] function that takes tabular data and generates dp based on that

## Analysis

**Comment by anuveyatsu** [comment]
INVALID as we have implemented generating `datapackage.json` in #63
