### ISSUE TITLE
Refactor to use now style error handling, messaging and spinner

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#101]
Switch use the now-cli approach

## Acceptance criteria

* [x] logger in `/bin/` modules replaced by new approach
* [x] error handling done by `lib/utils/error.js` module

## Tasks
* [x] use console.log for normal messages and error and info for other stuff ...
* [x] spinner lib/utils/output/wait.js for spinner
* [x] messaging
  * [x] lib/error.js -- we should move to libs/utils/error.js
  * [x] lib/utils/output/info.js
  * [x] lib/utils/output/error.js
* [x] And as practice use in bin/data-push.js

**Comment by anuveyatsu** [comment]
FIXED in #105
