### ISSUE TITLE
Resource supports loading xls

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#102]
Support reading XLS files.

```
const res = Resource.load(/path/to/excel-file.xlsx
res.rows()
```

Qus:

* What about sheet number etc

## Acceptance criteria

* [x] I can use `xlsx` files as resources
* [x] Can use `xls` as resources

## Tasks

**Requires Resource.buffer #113**

* [x] install and setup `sheetjs` lib for `xlsx` format
* [x] create `xlsx.js` module with parser function
* [x] add `xlsx` parser function into `parserDatabase`
* [x] test

## Analysis

Use sheetjs

**Comment by anuveyatsu** [comment]
FIXED. We can now load xlsx/xls format files with `Resource` class. E.g., we can run `data cat in.xlsx stdout`.
