### ISSUE TITLE
Refactor info command to use new data lib and 

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#107]
Still works as before:

```
data info path-or-url-or-datahubid
// prints to stdout ...
```

## Tasks

* [x] (Prerequisite) Package lib - README support #106
* [x] Update bin code to create Package and do render (get rid of lib/info.js) - rought version (just working with packages)
* [x] isPackage method done properly: moved to data lib from bin and has proper tests 
* [x] `info(...)` supports resources as well as packages - maybe split into infoPackage() and infoResource() methods
* [ ] (?) reinstate support for datahub paths (this is more of a parseIdentifier issue in data lib - once done we get this for free)

**Comment by rufuspollock** [comment]
@anuveyatsu can you take on rest of this 😄

**Comment by anuveyatsu** [comment]
@rufuspollock fixed tasks, but not the last one, which is probably should be fixed in a separate issue. At the moment, we do not support `datahub-id`. Can we close that issue for now?

**Comment by anuveyatsu** [comment]
Closing for now as FIXED - info works for Resources and Packages
