### ISSUE TITLE
Refactor get command to use new lib structure and new api

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#108]
We want our `get` command to work with recently refactored lib structure and api

## Acceptance criteria

* [x] I can get a package by `$ data get {datahub-url}` - see #144 
* [x] I can get a package by `$ data get {github-url}`
* [x] I can get a package by `$ data get {any-url-to-datapackage}`
* [x] I can see help for get command by `$ data get --help`

## Tasks

* [x] refactor-move logic re saving files checking dest into `/bin/data-get.js`
* [x] `/lib/get.js` should be minimal function that takes dataset object and returns list of files to
* [x] refactor `bin/data-get.js` so help works

## Analysis

// OLD

We now have `Package` class that should be used for working with data packages. We should instantiate the class from `bin/data-get.js` and then do save:

```javascript
const pkg = await Package.load(pkgid)
pkg.save()
```

Refactor `Package` class to have `save` method:
Also, need to reuse old `checkDestIsEmpty` function to make sure we can write into destination:

```javascript
save() {
  const path_ = path.join(this.identifier.owner, this.identifier.name)
  const isEmpty = checkDestIsEmpty(path_)
  if (isEmpty) {
    let dest = path.join(path_, 'datapackage.json')
    fs.write
  } else {
    // error saying dest is not empty
  }  
  ...
}
```

Reuse `parseIdentifier` function so we can handle any of `datahub`, `github` and `normal` urls.

**Comment by rufuspollock** [comment]
Waiting on server so moving to next milestone.

**Comment by anuveyatsu** [comment]
FIXED. Now we can do `get` from URLs (github, datahub and random) to get datasets.
