### ISSUE TITLE
Add tests with resource

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#109]
At the moment, we are testing push command against packaged dataset and virtual package. But we also want to have tests for packages with resources.

## Acceptance criteria

* [x] fully working tests in `/test/utils.datahub.test.js` for a package with a resource

## Tasks

* [x] create fixture data package
* [x] mock filedata for that package
* [x] mock rawstore api for that case
* [x] mock spec source api for that case
* [x] create a test

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datahq/datahub-cli/commit/41f250d2e597e3bad8237b515dfb9d4a950241b1
