### ISSUE TITLE
[push] Include README.md in push along with resources and metadata

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#110]
We should push README.md separately from datapackage.json. For now assume it is always `README.md`.

## Acceptance criteria

* [x] We push README (if it exists) along with datapackage.json and other files

## Tasks

* [x] refactor `push` function in `/lib/utils/datahub.js`
  * [x] if `README.md` exists load and add it into resources list
* [x] test it

## Analysis

If readme file exists, we assume it would be accessible with `readme` key from an instance of Package class. So when doing `push` we can check by `pkg.readme` if it exists.

```javascript
// lib/utils/datahub.js in push function:
if (pkg.readme) {
  const README = Resource.load({
    path: 'README.md',
    data: pkg.readme
  })
  resources.push(README)
}
```

**Comment by rufuspollock** [comment]
FIXED. Note we ultimately settled on inlining the README rather than pushing as a separate resource.
