### ISSUE TITLE
[push] Display upload progress to user

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#116]
At the moment, when pushing packages, especially big ones, it is not clear what's happening. We want to have a progress bar so users know which stage is being processed.

## Acceptance criteria

* [x] When I do push, I can see the progress of upload process

## Tasks

* [x] refactor `push` method of `DataHub` class in `datahub-client` library
  * [x] add a listener for `formData` and implement it along with the progress bar
* [x] refactor `data-cli` library to work with it

## Analysis

We will use `progress` npm package to implement the progress bar - https://www.npmjs.com/package/progress

See example here https://github.com/visionmedia/node-progress/blob/master/examples/download.js

Using the example above, implement progress bar here - https://github.com/datahq/datahub-cli/blob/master/lib/utils/datahub.js#L49-L82
Use `totalLength` for `total` parameter.

Not sure if we can use fetch here: https://github.com/github/fetch/issues/89

**Comment by anuveyatsu** [comment]
FIXED - will be available in release `>v0.8.2`

<img width="649" alt="screen shot 2018-03-30 at 16 15 20" src="https://user-images.githubusercontent.com/17809581/38134608-9e4a6c48-3435-11e8-84cf-ae57e64b1c0a.png">
