### ISSUE TITLE
npm run build script that compiles ES6 => ES5

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data-cli#118]
We want to have `npm run build` that compiles ES6 => ES5.  Otherwise, I think one cannot use it as a dependancy as Babel ignores node_modules.

## Acceptance criteria

* [x]  when I run `npm run build` it compiles ES6 => ES5 into `/dist/` dir.

## Tasks

* [x] install `babel-cli`
* [x] setup script in `package.json`: `build: babel lib -d dist`
* [x] run `npm run build` and verify

**Comment by Mikanebu** [comment]
FIXED
