### ISSUE TITLE
data configure command 

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#12]
We need to know user credentials like username and secret to be able to authenticate and publish data.

- Key variables: username, secret, server
- Location: ~/.datahub/config

Proposal:

```
data config
```

## Acceptance criteria 

- [x]  `data config`  asks user to enter config variables and then save it to disk.

## Tasks 

- [x] find config parsing library [1] 
  * think simple npm/ini lib would be more than enough https://github.com/npm/ini 
- [x] write tests [1] 
- [x] try to transform dpm python code for config into JS https://github.com/frictionlessdata/dpm-py/blob/master/dpm/config.py [3] 
- [x] updated README [1]

**Comment by zelima** [comment]
FIXED. for now `datahub --config path_to_config` does not work. will be implemented later

**Comment by anuveyatsu** [comment]
@zelima as per discussion with @rufuspollock we don't want to have `path_to_config` option. If it is not working and it is not clear how to fix it, can we remove this option (so it doesn't appear in `--help` output)?

**Comment by zelima** [comment]
FIXED. --config [path_to_config] removed

**Comment by zelima** [comment]
Refactor under now-cli

**Comment by zelima** [comment]
FIXED
