### ISSUE TITLE
[validate] Refactor to new bin approach and support data checking (for tabular)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#121]
## Acceptance criteria

* [x] I can run `data validate {path/to/dp}` and it validates my metadata + resources (data)

## Tasks

Refactoring

* [x] internally two function validateMetadata, validateData
* [x] Update validateMetadata to latest schemas
  * [x] maybe inline - i'm dubious if we need datapackage-js for this - we can just extract the relevant validate method into its own small lib file here (ultimately i hope this could be a tiny little lib that is reused)
* [x] validateData - Use tableschema to validate data (again we may wish to extract - or not)

Command line:

* [x] data validate {DP/DIR} => check metadata and then start checking all resources
* [x] data validate {FILE-PATH} - check if datapackage.json in *current directory* and then validate the file using that datapackage.json

**Comment by anuveyatsu** [comment]
FIXED. Metadata validation is done by extracting validation logic from `datapackage-js` library, while tableschema-js is used for data validation against given schema.
