### ISSUE TITLE
CSV parser supports dialect 

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#122]
See https://specs.frictionlessdata.io/tabular-data-resource/#csv-dialect

In terms of tests see what already existing in the python FD libs (and JS?)

Also see previous code here: https://github.com/frictionlessdata/datapackage-render-js/blob/0d05d7369245820e75b0683756c2518dede3ae3f/datapackage.js#L142

## Acceptance criteria

* [x] Can parse a CSV with semicolons
* [x] By default supports CSV with either unix or dos line terminators
* [x] Supports all of csv dialect

## Tasks

* [x] Add support for dialect (convert to csv parse parameters)

**Comment by anuveyatsu** [comment]
FIXED. Reused logic from https://github.com/frictionlessdata/datapackage-render-js/blob/0d05d7369245820e75b0683756c2518dede3ae3f/datapackage.js#L142 in mix with our `keyed` option. To use csv dialect, `resource` object's descriptor should have `dialect` property.
