### ISSUE TITLE
Resource.rows keyed option to return rows as objects instead of arrays

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#124]
Same as tableschema-js - https://github.com/frictionlessdata/tableschema-js/blob/master/src/table.js#L79

```javascript
if (keyed) {
        // TODO: schema.fieldNames to the mix!
        row = lodash.zipObject(this.headers, row)
      }
```

## Acceptance criteria

* [x] I can get rows as objects by: `myResourceObj.rows({keyed:true})

## Tasks

* [x] refactor parsers to get `keyed` option and return stream as array of objects
* [x] refactor methods for getting rows in Resource class to take `keyed` option
* [x] add tests

**Comment by anuveyatsu** [comment]
FIXED. Now it is possible to get rows as array of objects by passing `keyed` option: `myResourceObj.rows({keyed: true})`
