### ISSUE TITLE
[data] stream and rows are methods rather than getters

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#125]
A minor refactoring that is a prerequisite for other improvements e.g. #124 

## Acceptance criteria

* [x] `stream` & `rows` are methods instead of getters

## Tasks

* [x] make `stream` and `rows` getters in `Resource`, `ResourceLocal`, `ResourceRemote` and `ResourceInline` classes to be methods
* [x] refactor tests according to changes
* [x] refactor lib modules that depends on that changes

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datahq/datahub-cli/commit/42e9755554c61a6fb1b2f21a53f51a9339d36b6e
`rows` and `stream` changed to be methods and all modules within the lib that depends on these methods were refactored. In addition, `test/utils.data.test.js` tests were refactored.
