### ISSUE TITLE
`npm run pack` to build binaries is not working 

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data-cli#130]
When I run `pkg run pack` it gives me the following error: 
```bash
datahub-cli@0.1.0 pack /Users/Zhiyenbayev_mirza/Desktop/Datopian/src/datahub-cli
> pkg bin/data.js -c package.json -o packed/datahub

> pkg@4.1.3
> Error! Cannot stat, ENOENT
  /Users/Zhiyenbayev_mirza/Desktop/Datopian/src/datahub-cli/docs/config.md
  The file was required from '/Users/Zhiyenbayev_mirza/Desktop/Datopian/src/datahub-cli/bin/data-config.js'
```
Probably after refactoring code, we may miss to update configuration. 

Analysis: After removing `config.md`, it still errors: 
```bash
> pkg@4.1.3
> Error! TypeError: license.toLowerCase is not a function
    at isPermissive 
    at <anonymous>
```

## Acceptance criteria

* [x] `npm run pack` builds executables for macos and linux

## Tasks

* [x] debug why it is failing
* [x] remove config command and its logic
* [x] update version of pkg

**Comment by anuveyatsu** [comment]
FIXED - the reason was a bug in `pkg` library so we've updated version to `4.2.2`
