### ISSUE TITLE
Refactor normalize.js script for the new spec

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data-cli#131]
We want to add several functions into normalize.js script, so we can easily can fix data packages. 

## Acceptance criteria

* [x] Core data packages that did not pass a validation should be fixed with normalization command

## Tasks

* [x] analyse common errors that can be fixed with normalization script
* [x] create functions
  * [x] create function for `sources` property to generate `title`
  * [x] create function for `resources` property to generate `name`
  * [x] create function to fix  `name` property in `licences` to match this pattern: ^([-a-z0-9._/])
  * [x] create function to fix `resources:sources` to have `title`

## Analysis

According to the status of core data packages on https://github.com/datahq/core-datasets-tools/blob/master/status.csv, we have several common validation errors after updating the schema.
* `sources` property has a required field `title` - total 45 core data packages
* in `licences`, property `name` must follow the following pattern: ^([-a-z0-9._/]) - total 5 core data packages
* `resources` property has a required field `name` - total 3 core data packages

**Comment by anuveyatsu** [comment]
FIXED see https://github.com/datahq/core-datasets-tools/blob/master/status.csv for statuses
