### ISSUE TITLE
CLI set owner + ownerid for specstore api 

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#135]
At the moment, we are posting following to the specstore:

```
{
  "meta": {
    "version": 1,
    "owner": "90998f7f90e086bd5fc7c9075dfda43b",
    "dataset": "..."
  },
  "inputs": [
    {...}
  ]
}
```

However, `owner` property here is actually the `ownerid`. We want to set both with correct keys and values.

## Acceptance criteria

* [x] we hit specstore api with both `owner` and `ownerid` when pushing

## Tasks

* [x] refactor `DataHub` class so it sets `owner` and `ownerid` when instantiated
* [x] refactor `makeSourceSpec` method
* [x] refactor `bin/data-push.js` so it uses `owner` when instantiates `DataHub` class

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datahq/datahub-cli/commit/07af3ff0c344f652583dc751d1d5af5de888120d
