### ISSUE TITLE
Built binaries not functioning

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#136]
Binary executable is not working because we are using some of features that are not yet available in Node v8:
```
export const login = async function (apiUrl, authUrl) {
^^^^^^
SyntaxError: Unexpected token export
```

## Acceptance criteria

* using binary I can do:
  * [ ] login
  * [ ] push
  * [ ] cat
  * [ ] info

## Tasks

* [x] research what else we are using that is not available yet in Node 8
* [x] try to replace these syntaxes with older ones
* [x] build the package
* [x] test

**Comment by Mikanebu** [comment]
FIXED
