### ISSUE TITLE
Validate data package

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#14]
We want to have a command to validate `datapackage.json`, which tells publishers whether the descriptor is valid or not. If it is invalid, we want to see the source.

```
# validate a datapackage.json
# it is valid:
data validate
> It is valid!

# it is invalid:
data validate
> Abort and show useful list of validation errors

## richer version
# data validate [local path or dpid]
```

## Acceptance criteria

* [x] Passes on valid dp.json
* [x] Aborts with informative error on invalid dp.json

## Tasks

* [x] Check it is valid JSON (and report helpfully if not)
* [ ] Validate against schema (JS dp library should do this for us)
* [x] Nice output

## Analysis

We could use stand alone function from here - https://github.com/frictionlessdata/datapackage-js#validate

Catch errors - `(Error[]) - raises list of validation errors for invalid` so we can show errors.

**Comment by zelima** [comment]
FIXED in #43
