### ISSUE TITLE
[info] QA review 8 Aug 2017

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#142]
A. when running `data info` I expect help message, but results:
```
(node:27765) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'endsWith' of undefined
(node:27765) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

B. documentation is a bit confusing. Thought it was working for remote packages as well. Even though it does not if I try and info something non-existing Eg: `data info core/co2-ppm` (from help example) errors: 
```
(node:20707) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: ENOENT: no such file or directory, lstat 'core/co2-ppm'
(node:20707) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Acceptance criteria

* [x] `data info` without providing path, checks for `datapackage.json` in CWD
* [x] updated documentation for `info` command
 
## Tasks

* [x] refactore `data-info`
* [x] update  documentation for `info` command

**Comment by rufuspollock** [comment]
> A. when running data info I expect help message, but results:

We should do what other commands do and default to cwd if no path specified.

I also think we should make sure that info command, if given a directory, looks for datapackage.json in that directory (and only if that is not there does it fail).

> B. documentation is a bit confusing. 

Documentation needs updating. This is probably the priority here.

Note we no longer explicitly support datahub datasets via simple `owner/name`. See https://github.com/datahq/datahub-cli/issues/144 for more on this.

**Comment by Mikanebu** [comment]
FIXED
