### ISSUE TITLE
Rename Resource to File and Package to Dataset

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#145]
We want to rename `Resource` to `File` and `Package` to `Dataset`.

## Acceptance criteria

* [x] Renamed `Resource` to `File` and `Package` to `Dataset`
 
## Tasks

* [x] Rename `Resource` to `File`
* [x] Check test
* [x] Rename `Package` to `Dataset`
* [x] Check test

**Comment by Stephen-Gates** [comment]
Good idea. Those names cause much confusion in my circles.

**Comment by anuveyatsu** [comment]
FIXED in #148
