### ISSUE TITLE
CLI without Babel

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#152]
Almost all the code is already supported in Node v7.6 so there is very little reason to still use Babel. However, it is slowing down the library significantly so we want to start using our CLI without Babel.

## Acceptance criteria

* [x] no Babel is used to run commands and tests

## Tasks

* [x] replace unsupported syntax, e.g., inline `exports`
* [x] remove `dist` directory as not needed anymore
* [x] verify everything is working on None v7.6 and upper

**Comment by anuveyatsu** [comment]
FIXED in #153
