### ISSUE TITLE
data with different encoding than utf-8 does not work

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data-cli#154]
Starting from an error report in https://github.com/datahq/frontend/issues/58 of encoding issues in the frontend we have traced issue to a bug in the encoding detection here in the CLI (see 58 issue for details).

If data is saved in different encoding that `utf-8`, it will fail.

## Acceptance criteria 

* [x] we do not push data with strange characters 

## Tasks

* [x] Create failing test case by adding sample.csv with different encoding(`cyrillic` for example).
* [x] read `iconv` and `iconv-lite` documentation, and try out library [1]
* [x] if does not help, look for other libraries and try to solve [1]
* [x] prepare analysis and discuss whether we need to take care of this issue at all(it is better to ask user to use `utf-8` by default). [1]

## Analysis

As much as I know, after debugging the problem now with encoding in DataHub CLI.

First of all, it is related with `data.js` package, since it is responsible for instantiating File class. 
In `File` class, we have a method called `get encoding` which returns encoding for the given file. 

**Do you have an failing test yet? That is the FIRST thing to do -- actually get this to fail**

* First step: I replaced `chardet` library with `jscharded` since the second one has more encodings list and it has more stars. 
  * I tested with `windows Cyrillic`, `chardet` could not recognized it, when I used `jschardet`, it returns `ascii`
* Second step: I take a look on `stream` method, this is the part where we get our data
  * There are several packages such as `Iconv`, `iconv-lite` and `utf-8` to change encoding to `utf-8`, otherwise, it is not working. 
    * Tested with `cyrillic` for example. It could not change the encoding to `utf-8`. 
The best solution would be prompt user to use `utf-8`.

**Comment by rufuspollock** [comment]
@Mikanebu can you update on the status of this. Do you have a failing test? If so can you paste that or gist it?

**Comment by Mikanebu** [comment]
@rufuspollock according to my analysis above I do not have a failing test. I have checked manually that it works with any character if the file encoding is utf8. It does not work with non utf8 file encodings.

**Comment by Mikanebu** [comment]
@rufuspollock Created failing test in https://github.com/datahq/data.js/blob/fafe399408409061cc6ce2659c5d83313ea0f5ba/test/index.test.js#L181 and I am moving issue to backlog as it is not top priority atm and no clear fix

**Comment by anuveyatsu** [comment]
We've experienced it in QA tests:

* push csv with 'Western MAC OS Roman' encoding
  * use data from https://github.com/frictionlessdata/test-data/blob/master/data-files/csv/encodings/western-macos-roman.csv
  * 'utf-8' codec can't decode byte 0x8e in position 38: invalid start byte and test-western-macos-roman: 1 error(s) found.
* push csv with ISO8859 encoding
  * use data from https://github.com/frictionlessdata/test-data/blob/master/data-files/csv/encodings/iso8859.csv
  *  'utf-8' codec can't decode byte 0xe9 in position 38: invalid continuation byte and  iso8859: 1 error(s) found.

**Comment by zelima** [comment]
FIXED  https://datahub.io/zelima/iso

**Comment by rufuspollock** [comment]
@zelima @anuveyatsu i just commented in the PR for this as i'm not sure why fix was here rather than in data.js ...
