### ISSUE TITLE
[push] Pushing single csv file from URL does not work

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#155]
If I try to push some `csv` file from URL, it would error saying `ENOENT: no such file or directory, lstat 'https://some-url'`. E.g.,:
```
$ data push https://raw.githubusercontent.com/datasets/co2-ppm/master/data/co2-annmean-gl.csv
```

## Acceptance criteria

* [ ] I can push single csv file from URL

## Tasks

* [ ] analysis
* [ ] refactor `/bin/data-push.js` accroding to analysis below
* [ ] test cases for pushing remote single csv file
  * [ ] mock out

## Analysis

In https://github.com/datahq/datahub-cli/blob/master/bin/data-push.js#L39 we're checking if a provided path is for file and this is where the error is thrown. We need to add some logic to first check if given path is local or remote. If remote, we need to check if it's a file (by checking if it ends with `.ext`) - this also should fix possible issue with pushing remote data package (e.g., from github).

```javascript
const path = require('path')
const url = require('url')
const {isUrl} = require('data.js')
...
const fileIsRemote = isUrl(filePath)
let itIsFile
if (fileIsRemote) {
  const parsedUrl = url.parse(filePath)
  const pathPart = parsedUrl.path
  itIsFile = path.extname(pathPart) // if no extension, empty string evaluates to false
} else { // file is local
  itIsFile = fs.lstatSync(filePath).isFile()
}

if (itIsFile) {
  dataset = await prepareDatasetFromFile(filePath)
} else {
  dataset = await Dataset.load(filePath)
}
```

**Comment by rufuspollock** [comment]
INVALID - now have epic for this https://github.com/datahq/pm/issues/22
