### ISSUE TITLE
[get] Get command should support files

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#158]
As a Datar I want to get a data file locally ...

```
data get https://example.com/path/to/file.csv
data get https://datahub.io/owner/dataset/r/file.csv
data get https://github.com/...
```

## Acceptance criteria

* [x] i can get a single file with `data get` command

## Tasks

* [x] use `isDataset` method from `data.js`
* [x] create logic for case when URL is not dataset
* [x] tests

## Analysis

In `/bin/data-get.js`:

```javascript
...
const itIsDataset = isDataset(identifier)
if (itIsDataset) {
  // old code
} else {
  const file = await File.load(identifier)
  const destPath = [file.descriptor.name, file.descriptor.format].join('.')
  const stream = await file.stream()
  stream.pipe(fs.createWriteStream(destPath))
  savedPath = destPath
}
...
```

**Comment by anuveyatsu** [comment]
FIXED. If I do `data get https://datahub.io/core/co2-ppm/r/0.csv`, the first resource of `co2-ppm` will be saved at `./0.csv`.
