### ISSUE TITLE
Make interactive mode as optional

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#159]
When I push a single CSV file it works in the interactive mode by default. But we want it to be non-interactive with an option to pass `-i` flag for interactive mode.

## Acceptance criteria

* [x] when I do `data push myfile.csv` it works in non-interactive mode
* [x] when I do it with `-i` (or `--interactive`) flag it work in interactive mode

## Tasks

* [x] analysis
* [x] refactor `/bin/data-push.js` to use prompt only if in interactive mode

## Analysis

Setup the minimist to parse `interactive` keyword with an alias `i`, so then in `/bin/data-push.js`:

```javascript
// in prepareDatasetFromFile function
if (argv.interactive) {
  // Prompt user with headers and fieldTypes
  const questions = [ask('headers', headers), ask('types', fieldTypes)]
  const answers = await inquirer.prompt(questions)

  if (answers.headers === 'n' & answers.types === 'n') {
    // Maybe nicer exit - user has chosen not to proceed for now ...
    throw new Error('Please, generate datapackage.json and push.')
  }
}
```

**Comment by anuveyatsu** [comment]
FIXED. By default, pushing single file works in non-interactive mode. You can pass `--interactive` or `-i` flag for interactivity.
