### ISSUE TITLE
Only first sheet is available when working with Excel

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#162]
We want users to be able to select any sheet from their Excel files. At the moment, as it can be seen from https://github.com/datahq/data.js/blob/master/lib/parser/xlsx.js#L10-L12 we're using the first sheet for any given Excel file by default. There is no option to select other sheets.

## Acceptance criteria

* [x] I can select any sheet from my Excel file

## Tasks

* [x] Analysis
* [x] refactor xlsx parser in data.js repo
* [x] check tests + hand test

## Analysis

In https://github.com/datahq/data.js/blob/master/lib/parser/xlsx.js#L7 function, have interaction with users if provided excel file has more than 1 sheet:

```javascript
...
const inquirer = require('inquirer')
...
const xlsxParser = async (file, keyed = false) => {
  const buffer = await file.buffer
  const workbook = XLSX.read(buffer, {type: 'buffer'})
  let selectedSheetName = workbook.SheetNames[0]
  if (workbook.SheetNames.length > 1) {
    const answer = await inquirer.prompt([{
      type: 'list',
      name: 'sheetName',
      message: 'Please, select a sheet from your Excel file:',
      choices: workbook.SheetNames
    }])
    selectedSheetName = answer.sheetName
  }
  const sheet = workbook.Sheets[selectedSheetName]
  ...
}
```

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datahq/data.js/commit/2e67f8a55fbcd898ff7b80f983f5b9bb454f6e54

<img width="344" alt="screen shot 2017-09-06 at 12 32 52" src="https://user-images.githubusercontent.com/17809581/30097687-a174554a-9300-11e7-838a-73df3945d49d.png">

**Comment by anuveyatsu** [comment]
Although this implementation is useful for `cat` and `info` commands, we want to have the option to pass sheet index so we don't get prompted by the inquirer. E.g., when pushing Excel files, we need to process the first sheet and add its schema in Excel resource. After that, we need to process other sheets and add their schemas in source spec.

This will be fixed in https://github.com/datahq/data.js/issues/13

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datahq/data.js/issues/13
