### ISSUE TITLE
Set output formats: zip, sqlite

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#165]
We want our users to be able to define output formats when pushing their datasets. By default, for tabular files we have set CSV and JSON formats, but we also want to have optional zip, sqlite formats.

## Acceptance criteria

* [x] I can do `data push mydataset --sqlite | --zip` and my pushed dataset will have outputs in required formats (can be multiple)

## Tasks

* [x] refactor `/bin/data-push.js` to be able to provide `--sqlite, --zip` options
* [x] refactor `/lib/utils/datahub.js` to handle new options
* [x] refactor `makeSourceSpec` function to include `outputs` attribute

## Analysis

Refactor minimist logic to handle new options:

```javascript
const argv = minimist(process.argv.slice(2), {
  string: ['push'],
  boolean: ['help', 'debug', 'interactive', 'sqlite', 'zip', 'rdbms'],
  alias: {help: 'h', interactive: 'i'}
})
```

then pass values of these new options when doing push:

```javascript
const outputs = {
  sqlite: argv.sqlite,
  zip: argv.zip,
  rdbms: argv.rdbms
}
await datahub.push(dataset, outputs)
```

In the `makeSourceSpec` handle setting output formats:

```javascript
const makeSourceSpec = (rawstoreResponse, ownerid, owner, dataset, outputs) => {
  ...
  const outputFormats = outputs.forEach(output => {
    ...
  })
  
  return {
    meta: {...},
    inputs: [...],
    outputs: ...
  }
}
```

**Comment by anuveyatsu** [comment]
Implemented for `zip` and `sqlite` formats. `rdbms` part is not yet fully analysed

**Comment by anuveyatsu** [comment]
FIXED - closing for now as cli part is done here. We will reopen if something comes up after backend implementation.
