### ISSUE TITLE
Set schemas for Excel file's sheets

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#166]
When pushing Excel files, we need to generate and push schema for all sheets of the file. We want to push schemas for all sheets within a source spec.

E.g., we have an Excel file with 2 sheets:

```javascript
// datapackage.json resource property:
{
  resources: [
    {
      name: 'my-excel',
      path: '...',
      format: 'xlsx',
      ...
    }
  ]
}
```

and then in the source spec:

```yaml
processing:
 - # Processing steps that need to be done on sources to get proper data streams
   input: <source-resource-name - e.g. `my-excel-resource`>
   output: <destination-resource-name - e.g. `my-excel-resource-sheet-1`>
   tabulator: # Currently we're only supporting tabulator transformations
     # These are sample options for tabulator, see its docs for all available options
     headers: 2 
     sheet: 1
   schema: # Overwrite schema for resource
     fields:
       - name: bla
         type: string
       # table schema
```

## Acceptance criteria

* [x] when I push Excel files all its sheets information (as per source spec requirements) are included in source spec

## Tasks

* [x] analysis
* [x] refactor `/lib/utils/datahub.js` per algorithm below
  * [x] create `handleSheets` function for iterating through Excel's sheets and creating processing objects

## Analysis

Algorithm:

```
1. when calling makeSourceSpec pass dataset object
2. iterate through dataset's resources and identify excel resources
3. for each excel resource, figure out number of sheets it has
4. for each sheet, create processing items:
  * input: resource name
  * output: resource name + "_sheet_" + sheet number
  * tabulator: ...
  * schema: ...
5. proceed further as usual
```

**Comment by anuveyatsu** [comment]
FIXED. This is fixed to handle all sheets of given Excel file. However, we have changed the behaviour in the next issues - by default we only process the first sheet with an option to select several or all sheets (https://github.com/datahq/datahub-cli/issues/185)
