### ISSUE TITLE
[push] Setup schedule - crontab in source spec

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#168]
*As a publisher I want to be able to setup schedule so my remote file gets re-imported regularly into DataHub.*

* *Decide if it should have default and if users should be able to set it.*
  * No default, but users can specify how often it should be imported: `--schedule=...` -  i think it should explicit, otherwise we don't know if re-import is needed.

## Acceptance criteria

* [x] When I push remote file, I can pass an option saying how regular my file should be re imported.

## Tasks

* [x] refactor `/bin/data-push.js` - minimist + passing `schedule` to datahub utility
* [x] refactor `/lib/utils/datahub.js` so `makeSourceSpec` handles `schedule` poperty

## Analysis

Handle `--schedule` value in `/bin/data-push.js` and add it in options variable:

```
{
  ...,
  schedule: argv.schedule
}
```

Users must pass `--schedule` in cron format surrounded with quotes so spaces are allowed:

```
data push mydataset --schedule="0 0 * * *"
```

Expect `options.schedule` in `makeSourceSpec` function in `/lib/utils/datahub.js`:

```javacript
const schedule = options.schedule ? {crontab: options.schedule} : undefined
```

---

# // OLD

Set it up in `/bin/data-push.js`:

```javascript=
const argv = minimist(process.argv.slice(2), {
  string: ['push'],
  boolean: ['help', 'debug', 'interactive', 'schedule'],
  alias: {help: 'h', interactive: 'i'}
})
...
await datahub.push(dataset, argv.schedule)
```

And then we need to pass it over to `makeSourceSpec` function in `/lib/utils/datahub.js`:

```javascript=
...
const spec = makeSourceSpec(rawstoreUploadCreds, this._ownerid, this._owner, dataset.descriptor.name, schedule)

...

const makeSourceSpec = (rawstoreResponse, ownerid, owner, dataset, schedule) => {
  ...
  return {
    meta: {
      version: 1,
      ownerid,
      owner,
      dataset
    },
    inputs: [
      {
        kind: 'datapackage',
        // Above we set the "name" for the data package resource to be
        // datapackage.json so we use that name to look it up in rawstoreResponse
        url: rawstoreResponse['datapackage.json'].rawstore_url,
        parameters: {
          'resource-mapping': resourceMapping
        }
      }
    ],
    schedule: {
      crontab: schedule
    }
  }
}
```

**Comment by zelima** [comment]
@anuveyatsu I'm removing this from "Trial automation of core data scraping" EPIC as Scheduled time is predefined in `.datahub/flow.yaml` and used from there. So this becomes standalone issue or maybe part of `data push <<url>>`

**Comment by anuveyatsu** [comment]
FIXED. Now publishers can pass `--schedule` options in cron format, e.g., `data push mydataset --schedule="0 0 * * *"`
