### ISSUE TITLE
[docs] update/improvements in help messages

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#171]
* data push help message is not clear and short
* data normalize - poor CLI documentation at basic help screen (need more info - normalizes data package against spec 1.0)

## Acceptance criteria

* [x] data push help message is clear and thorough
* [x] data normalize help message is good, with Usage, Option, Examples sections

## Tasks

* [x] docs for push - add real example, providing path and explain path options
  * [x] also take a look at examples in the main help message
* [x] docs for normalize - analyse..

**Comment by Mikanebu** [comment]
FIXED, `data push` and `data normalize` help messages updated
