### ISSUE TITLE
Improvements to normalize - 16 Sep 2017

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#174]
We want to improve our `data normalize` command to do more tasks. 

## Acceptance criteria

* [x] `data normalize` with additional functions
  * [x] author merges into contributors 
  * [x] url on resources converts to path
  * [x] check for `title` property in `contributors` since it is required

## Tasks

* [x] analysis
* [x] author merges into contributors 
* [x] url on resources converts to path
* [x] check `title` property in `contributors`

## Analysis
> Just tried normalize on https://github.com/datasets/employment-us
>* [ ] author not merged into contributors automatically
>* [ ] url on resources not auto-converted to path (this is a really major one)
>* [ ] *probably more - @Mikanebu do the normalize yourself and check the diff*

For all core datasets, we are automated normalization script. For now, I will implement this normalization functions. 

I will folllow our convention for function name
* `normalizeContributors`
pseudo code
```
check for `contributors` property
if yes: then check `author` property
  if yes: merge `author` into `contributors`
  if no return dp
```

* `normalizePath`
```javascript
const normalizePath = dp => {
  for (const idx in dp.resources) {
    if(dp.resources[idx].path){
      return dp
    }
    else {
      dp.licenses[idx].path = dp.licenses[idx].url
  }
  return dp
}
```

* `normalizeContributorTitle`
```
const normalizeContributors = dp => {
  for (const idx in dp.contributors){
    if(dp.contributors[idx].title){
      return dp.contributors[idx].name = dp.contributors[idx].name.toLowerCase().replace(/\s/g, '_')
    } else {
    dp.contributors[idx].title = dp.contributors[idx].name.toLowerCase().replace(/\s/g, '_')
  }
  return dp
}
```

**Comment by Mikanebu** [comment]
FIXED, now, normalize script does the following: `author` merges into `contributors`, `url` on resources converts to `path`, add contributors `title`
