### ISSUE TITLE
[EPIC] Split out CLI lib as standalone library

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#178]
At some point, we will need to have standalone API for all CLI functionalities and tools and thin wrapper for CLI to use it. 

This will be useful for users that might need to communicate with datahub.io without using CLI as well as for us when we introduce browser (or other) UI.

## Acceptance criteria

* [x] this library is CLI only
* [x] all other modules are moved to a new library called "datahub-client"

## Tasks

* [x] split out DataHub related modules into new library called "datahub-client"
* [x] make sure only CLI related modules remain in this library
* [x] fix tests
* [x] clean dependancies

**Comment by anuveyatsu** [comment]
FIXED, now this lib contains minimal CLI related modules. All DataHub related modules were moved to a new library here - https://github.com/datahq/datahub-client
