### ISSUE TITLE
[get] Bugs of get command

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#179]
1) We have unhandled errors in case the URL is invalid - it says `UnhandledPromiseRejectionWarning` and loading forever

`data get https://github.com/datasets/finance-fix` results with 
```
⠙ Loading...(node:17982) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): FetchError: invalid json response body at https://pkgstore.datahub.io/core/finance-fix/latest/datapackage.json reason: Unexpected token < in JSON at position 0
(node:17982) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

or `data get core/finance-vix` results with 
```
⠋ Loading...(node:18009) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, lstat 'core/finance-fix'
(node:18009) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

2) When I do get from datahub.io it has weird behaviour:

* it creates following directories: `https:` => `pkgstore.datahub.io` => `core` => ...

## Acceptance criteria

* [x] error is handled by displaying some useful message
* [x] when i do get from datahub, it puts files in logical order: `owner/name/`

## Tasks

* [x] handle the error in the top level: `/bin/data-get.js` wrap the get method
* [x] do analysis on get command's saving files in the wrong way
* [x] refactor `saveIt` method in `/bin/data-get.js`

**Comment by anuveyatsu** [comment]
FIXED
