### ISSUE TITLE
Data push-flow

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#184]
As an Admin I want to define source-spec for dataset, that has remote resources and needs to be constantly updated, and push to datahub with simple command so that I'm able to run pipelines with desired specifications

## Acceptance Criteria

* [x] able to pus with source spec defined by me (not autogenerated)

## Tasks

* [x] functionalty for reading `flow.yaml`
* [x] bin handles with `data push-flow` 
* [x] docs
* [x] tests

## analysis

command: `data push-flow [PATH]` . awaits that there is `.datahub.flwo.yaml` and `datapackage.json` in  [PATH] or working directory
