### ISSUE TITLE
Data normalization script improvements 

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data-cli#186]
We want to handle cases with `licenses` and `sources` property. So  `source.web` which should be replaced with `source.path`,  `license` property as a string, but according to specs it should be called `licenses` (plural) and be an array of objects according to the 

## Acceptance criteria 

* [x] `sources` property `sources.web` replaces to `sources.path`
* [x] `license` property is `licences` and it is array of objects

## Tasks

* [x] merge `normalizeLicenseName` into `normalizeLicenses`
* [x] refactor `normalizeSources`

## Analysis 

> add normalization of `source` property - some datasets has `source.web` which should be replaced with `source.path`
> add normalization of `licenses` property - at the moment some datasets has `license` property as a string, but according to specs it should be called `licenses` (plural) and be an array of objects.

Refactor sources

```
const normalizeSourcesPath= dp => {
  for (const idx in dp.sources) {
    if (dp.sources[idx].web) {
      dp.sources[idx].path = dp.sources[idx].web
    }
  }
  return dp
}
```

Refactor licenses
```
const normalizeLicensses = dp => {
  if (dp.license) {
      dp.license = dp.licenses
    }
  }
  return dp
}
```

**Comment by Mikanebu** [comment]
FIXED, `sources.web` merges into `sources.path`, plus normalized `licenses` property according to the spec v1
