### ISSUE TITLE
Analysis and implementation on how normalize script could be split out from datahub-cli

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data-cli#188]
We want to split out normalize script from datahub-cli so it will be an independent module. 

## Acceptance criteria

* [x] Clear analysis on how to split out normalize script from datahub-cli
* [x] `normalize` is removed from datahub-cli
* [x] new repo `datapackage-normalize-js`

## Tasks

* [x] analysis
* [x] review from anu
* [x] remove completely `normalze` command from datahub-cli
* [x] create new repo `datapackage-normalize-js` and move eveything there

### Splitting out

* Create new repo `normalize.js`
* Structure will be in the following form:

```
lib/index.js
test/index.test.js
package.json
.travis.yml
```

### Tasks

* Move `lib/normalize.js` from the `datahub-cli`  to `lib/index.js`
* Update `bin/data-normalize.js` to require `const {normalize} = require('normalize.js')`
  * Install from npm once published
* Write README document for this repo - describe all public functions:
  * how each of them can be used + purpose

### Publishing into npm

Since we are using independent functions, it is ready to publish on npm:

* `normalize.js` is already taken so use another name:
  * `data-normalize`
  * `normalize-dp`
  * `normalize-js`
  * `data.norm.js`
  * `data.normalize.js`
  * `data.normalize`

**Comment by Mikanebu** [comment]
FIXED, repo for normalize is created here https://github.com/datahq/datapackage-normalize-js
