### ISSUE TITLE
Handle pushing remote url

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#189]
We want to be able to push files from URLs, e.g., `data push https://example.com/myfile.csv`. At the moment, we only handle local files (and local datasets).

## Acceptance criteria

* [x] I can push remote files to DataHub

## Tasks

* [x] refactor `/bin/data-push.js`
* [x] remove remote resources in `/lib/utils/datahub.js`

## Analysis

Algorithm in `bin/data-push.js`:

* get the first argument and check if it is a file path OR a URL
  * YES - go to `prepareDatasetFromFile` function
  * NO - proceed as local dataset

Looking at `flow.yaml` file, the `data push URL` algorithm would be:

1. Identify it’s a URL (assume yes)
2. Generate a datapackage for it
3. Post `datapackage.json` **only** to AWS
4. Generate source spec like here - https://github.com/datasets/finance-vix/blob/master/.datahub/flow.yaml
5. Post source spec to specstore
6. Finish

**Comment by anuveyatsu** [comment]
FIXED - see two identical datasets:

- pushed as local file - https://datahub.io/anuveyatsu/sample-cowardly-dog-6
- pushed as remote file - http://datahub.io/anuveyatsu/sample-strong-stingray-63
