### ISSUE TITLE
Implement push commands

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#19]
The actual implementation of functions for `datahub push` command.

## Acceptance criteria

* [x] I can get upload URL from `../authorize/`

## Tasks

* [x] load config function
* [x] check dp exists function
* [x] authentication
* [x] collect file info
* [x] authorize

## Analysis

Use previous implementations ( #10 #14 #15 #16 ) 

* `datahub push`:
  * no dp.json - default: scratchpad package
  * if there is a dp.json then use it (check package name and publish under it)
* `datahub push my-data-package`
  * no dp.json - generate descriptor using `my-data-package` from user input
  * with dp.json - use existing one
    * if `my-data-package` does not match `name` in dp.json then throw an error (?)

### Naming data files when reading from stdin

We can use some standard names, e.g. `data`. 
**Outcomes:** assuming a publisher has only one scratchpad data package, we will be overwriting `data` file every time he/she pushes something from stdin.

### Which data files to publish (when not reading from stdin)

All accepted data files (csv, tsc, json, topojson, geojson ...) from current directory + from `/data/` directory. We may make it a standard.

### Where to generate dp.json

We could generate dp.json in CLI so we do all validation operations here.

**Comment by zelima** [comment]
@anuveyatsu think this is missing one more user story:

* *As a publisher I want to be able to publish data directly from stdin*

```
cat myfile.csv | datahub push
```
I wander how this files should be named on bitstore. (is there way to get name???)


Besides this:

`datahub push` - without dp.json questions: 
  - what should this publish - csv file in current working directory?
  - what if there are multiple of them, which one should we publish, all of them?
  - what about the non csv file should we publish them to?
  - what if files are placed inside folders? should we publish them as well?
    - probably no, cause what if user accidental types `dpm push` in `/` dir. we can not publish all of his data from hard disk :)
- `datahub push my-data-package` questions
  - pretty much all questions from above 
  - plus should this happen on the CLI side or is it better to handle this on server side?

Personally I think this should not go in MVP - too much questions and analysis to do and think even after analysis it will be very painfull to implement.

For now I would stick with only `cat myfile.ext | datahub push` and `datahub push` with valid datapackage as they seem pretty straightforward to implement.
What do you think? cc  @rufuspollock @Mikanebu

**Comment by anuveyatsu** [comment]
@zelima I have updated description/analysis of this issue according to your feedback. I still think we need all that features described above, but yes probably first we should do `stdin => push to server` part.

**Comment by anuveyatsu** [comment]
Closing for now - most work is done and remaining tasks will be implemented in #16
