### ISSUE TITLE
Create a HTML writer

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#191]
We want to have writer that will dump csv data to HTML table. We also want that table to have Bootstrap classes so when it is rendered with Bootstrap css it looks great:

```html
<table class="table table-stripped table-bordered">
  <thead>...</thead>
  <tbody>...</tbody>
</table>
```

## Acceptance criteria

* [x] I can do `data cat my.csv my.html` and get html-ed table version with Bootstrap classes so it renders nicely

## Tasks

* [x] create tests for HTML writer
* [x] create HTML writer in `/lib/cat.js`
* [x] refactor `/bin/data-cat.js` to use html writers

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datahq/datahub-cli/commit/0c3c79aeb7eea311541388c0d4e42f3f7ad28698
