### ISSUE TITLE
[info] data info command improvements

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#192]
* [x] data info </path/to/datapackage/> works (i.e. path to data package without datapackage.json works locally and remotely)
* [x] data info {file} prints out metadata then just cats the first 10 lines
  * Should be sort of identical (as much as we can) to the info we output for a resource in: `data info {datapackage}`
* [x] data info {file-online} should work - can we use as much info from "headers" as possible - often this gives filesize, type etc etc
  * *behaving identical as for local files - prints out descriptor + 10 lines of data*

*Note: this work will be useful for `data push url`*

## Acceptance criteria

* [x] above all works

## Tasks

* [x] test out what's still not working
* [x] refactor `lib/cat.js` so ascii writer takes limit argument to specify how many rows we want to print
* [x] refactor `lib/info.js` so we can tell the writer how many rows we need, e.g., 10
* [x] refactor `bin/data-info.js` for handling files
  * [x] add schema
  * [x] print out schema
  * [x] print out first 10 rows of data file

**Comment by anuveyatsu** [comment]
FIXED:

* `data push path/to/dataset` works without having `/datapackage.json` in the end both for local and remote datasets
* `data push path/to/file` works with printing out file desriptor + 10 lines of data. Works identically both for local and remote files.
