### ISSUE TITLE
Implement "format" option for File objects

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#197]
As https://github.com/datahq/data.js/issues/18 is implemented we need to add `--format` option in the CLI so publishers can do, e.g., `data push URL --format=csv`. We need to refactor following commands as they use File classes:

* in `cat` command
* in `push` command
* in `get` command - when getting single file
* in `info` command
* `init` (?) - init needs major refactoring

## Acceptance criteria

* [x] I can push remote files without conventional filename with `--format=csv` option so it is treated as CSV - e.g., https://www.eia.gov/totalenergy/data/browser/csv.php?tbl=T02.01

## Tasks

* [x] in `cat` command
* [x] in `push` command
* [x] in `get` command - when getting single file
* [x]  in `info` command

**Comment by anuveyatsu** [comment]
FIXED
