### ISSUE TITLE
Notify users about new versions of the data CLI tool

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#198]
User story: as a Publisher, I want to get notified about CLI tool updates so I always use the bug-free and improved software.

I cannot know if a newer version of the data-cli tool was released unless I visit the website or go to releases page (or read gitter channels for updates).

## Acceptance criteria

* [x] when there is a new version of the CLI is available, I get a warning about it
* [x] the warning includes instructions on how to get the update

## Tasks

* [x] create module that will check updates by comparing the latest available version with the current one
* [x] write instructions on how the update can be done
  * [x] for NPM
  * [x] for Unix
  * [x] for Windows
* [x] implement checking update on each CLI run (with caching of 1h)

## Analysis

Using https://www.npmjs.com/package/update-notifier package we can easily implement notifications with custom messages (instructions):

```javascript
const updateNotifier = require('update-notifier')
const pkg = require('./package.json')

module.exports = () => {
  // Depending on running OS show appropriate instructions:
  let instructions = 'If you installed data tool using NPM, just run `npm update -g data-cli`'
  if (process.platform === 'darwin') {
    // Instructions for macos:
  } else if (process.platform === 'linux') {
    // Instructions for linux:
  } else if (process.platform === 'win32') {
    // Instructions for windows:
  }

  const notifier = updateNotifier({
    pkg,
    updateCheckInterval: 1000 * 60 * 60 // 1h
  })

  if (notifier.update) {
    console.log(`Update available: ${notifier.update.latest}`)
    console.log('Please, follow these instructions to get the update:\n' + instructions)
  } else {
    return
  }
}
```

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datahq/data-cli/releases/tag/v0.7.4
