### ISSUE TITLE
Create a skeleton for the project

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#2]
Create a skeleton based on https://github.com/frictionlessdata/dpm-js repo.

## Acceptance criteria

* [x] skeleton as on `dpm-js` lib
* [x] `datahub` command runs
* [x] Tests: one basic test to show how it is done
* [x] `help` command - automatically provided by commander
* [x] `version` automatically provided by commander  

## Tasks

* [x] create `/bin/datahub.js` that logs 'Welcome to Datahub'
* [x] create `/tests/test_lib.js` with basic test init
* [x] create `/lib/index.js` with get functions (logs getting data for you) 

## Analysis

Project sceleton 
```
datahub-cli
└───bin
│   │   datahub.js
└───lib
    │   index.js
└───test
    │   test_lib.js
│   .gitignore
│   .travis.yml
│   package.json
│   README.md
```

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datopian/datahub-cli/commit/cca76e5c1c4c31863a12e2a497893b7e93bc8763
