### ISSUE TITLE
Include findability in metadata for presigned POST requests 

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#201]
We need to know that dataset is private: https://github.com/datahq/datahub-cli/blob/master/lib/utils/datahub.js#L152

## Acceptance criteria

* [x] reqest body inqludes findability

## Tasks

* [x] update piece of code like below
* [x] update tests if neccessary 

```
// CLI
const body = {
      metadata: {
        owner: this._ownerid,
        findability:  this._findability
      },
      filedata: fileData
    }

const res = await this._fetch('/rawstore/authorize', token, {
      method: 'POST',
      body
    })
```

**Comment by zelima** [comment]
FIXED
