### ISSUE TITLE
Write PreSigned URL in source-spec when needed

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#202]
For private datasets that are stored on rawstore under private ACL, we need pre-signed URL for the assembler to read the data. So before writing the resource and datapackage.json URLs into source-spec we need to request presigned URL https://github.com/datahq/datahub-cli/blob/master/lib/utils/datahub.js#L211

## Acceptance Criteria 

* [x] source-spec includes presigned URLs if necessary 

## Tasks

* [x] Before assigning URLs to source spec send Request to `checkurl` API (prob https://api.datahub.io/rawstore/signurl)
* [x] update test if neccessary

**Comment by zelima** [comment]
FIXED
