### ISSUE TITLE
Set dataset name when pushing single files

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#204]
At the moment, if we push a single file it auto-generates a dataset name. This is very useful but in some cases, users may want to set their own dataset name so they can control it, e.g., repush to the same dataset later.

## Acceptance criteria

* [x] when I push a single file it prompts me to confirm dataset name and title
* [x] I also can set name with `--name=mydataset` option

## Tasks

* [x] refactor `prepareDatasetFromFile` function accroding to analysis

## Analysis

* Check if `name` property is provided
  * YES - use it as name
  * NO - prompt user to confirm auto generated name (default) or he should type new one
* Construct title from name and confirm with user (by replacing `-` with space and capitalizing)

**Comment by anuveyatsu** [comment]
FIXED. Will be available in the next release.

Behaviour when pushing single file:

* Check if `name` property is provided
  * YES - use it as name
  * NO - prompt user to confirm auto generated name (default) or he should type new one
* Construct title from name and confirm with user (by replacing `-` with space and capitalizing)
