### ISSUE TITLE
change cli to push public by default

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data-cli#207]
We want to have `data push` command default to `published`. 

## Acceptance criteria

* [x] `data push` - by default `published`

## Task 

* [x] refactor `data-push.js` to make `published` by default 
* [x] update help message
* [x] update README
* [x] update docs in the frontend

**Comment by Stephen-Gates** [comment]
Not a fan of this idea. Publishers like to check things are right before showing the world. What's the thinking?

**Comment by rufuspollock** [comment]
@Stephen-Gates my logic was that people have a bit of a counter-intuitive experience of pushing something and it being invisible to the world on their profile page (it not being obvious that datasets are hidden by default).

Thus the idea was to switch to public by default with continued support for pushing as unlisted or private so that users who wanted that could just do `data push --findability=unlisted`.

What do you think? Your thoughts here really welcome.

**Comment by Stephen-Gates** [comment]
My perference is for safe defaults until there is a full command set. Eg how do I delete, rename, change, etc something that I made public by mistake?

Perhaps the user could set their preference.

**Comment by rufuspollock** [comment]
@Stephen-Gates great points and very good guidance on what a new user would be thinking. We'll think a bit more before we implement here.

**Comment by zelima** [comment]
@anuveyatsu the latest commit should fix this, right? can we close?

**Comment by anuveyatsu** [comment]
FIXED starting from v0.9.4
