### ISSUE TITLE
Data push xlsx file with sheet option

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data-cli#211]
We want to fix bug in `data push` excel file when we passing sheets option which is out of range.

## Acceptance criteria

* [x] `data push` with sheets option works fine

## Tasks

* [x] refactor `datahub-client.js` to check for sheets size and throw error if it is out of range
* [x] refactor `datahub-cli` to correctly parse sheets

## Analysis

Not human readable error message when I run `data push invalid-data-format-xlsx/data.xlsx --sheets=2` where sheet=2 does not exist
`> Error! sheets.split is not a function`

* The abovementioned error throws when typeOf sheet is `number`. So I need to make it string to pass on our function. This work will be done here.
* We need to change the length of sheets to passing sheets option params, so we can stop process and throw error when it is out of range. This part will be done in `datahub-client`.

**Comment by Mikanebu** [comment]
FIXED, now if we pass sheets which is out of range, for example data push data.xlsx --sheets=2(data.xlsx file has only one sheet), it throws error `> Error! sheet index 2 is out of range
`
