### ISSUE TITLE
Misc improvements from ux analysis 

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data-cli#212]
We want improve help message and error message

## Acceptance criteria

* [x] `data -h` is available
* [x] `data push` error message improved to
`> Error! No datapackage.json at destination.` when there is no `datapackage.json`
* [x] `format` option removed and fixed headings on `data get` help message
* [x] `data login` help message headings fixed
* [x] `data cat` with invalid url, throws readable error message

## Tasks

* [x] add `data -h` command
* [x] `data push`, when there is not `datapackage.json` it throws `> Error! No datapackage.json at destination`
* [x] headings in help messages fixed
* [x] `data cat` with invalid url throws `> Error! Invalid url`

## Analysis

* data command -h does not work
* `data push`
  * when there is no `datapackage.json`, error message is not super helpful
  `Error! ENOENT: no such file or directory, open '/Users/Zhiyenbayev_mirza/Desktop/Datopian/src/pm/qa-data/datapackage.json`. 
Could we make it more human readable like
 `fatal: No datapackage.json at destination.`
  * ~~Invalid metadata error message needs improvements
  `> Error! Unexpected end of JSON input`~~
* `data get`
  * `--format` option is extra in help message
  * help message has heading `## Example:`
* `data cat`
  * When I run invalid url, it gives me this error
  `Error! Invalid opening quote at line 1`
* `data login`
  * [minor-bug]help message has unprocessed markdown elements 
  `## Options:`

**Comment by Mikanebu** [comment]
`data push` error message fixed here https://github.com/datahq/data.js/commit/2c73acafd5e4ce1af9d140dc81d741684f223ba9

**Comment by Mikanebu** [comment]
FIXED, I moved last  task about data cat into https://github.com/datahq/datahub-cli/issues/220

**Comment by zelima** [comment]
@Mikanebu are you sure about issue number? 220 says Return full URL for showcase page once pushed
