### ISSUE TITLE
[push] "data push invalid_url" - publishes successfully without any error

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data-cli#214]
When I run `push` command on invalid URL `data push https://github.com/datasets/testtest`, it publishes anyway: https://datahub.io/Mikanebu/testtest-rare-eel-6
However, I expect it to fail saying that provided URL is invalid or similar.

## Acceptance criteria

* [x] running this command throws error with clear message: `data push https://github.com/datasets/testtest`

## Tasks

* [x] create a helper function that check a given URL in `/lib/utils/common.js` in `datahub-client` library
* [x] call that function for `path` of each `remote` resource in the `push` method of `DataHub` class

**Comment by anuveyatsu** [comment]
FIXED - will be available with the next release of the CLI
