### ISSUE TITLE
[cat] sheet option for excel

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#217]
As a Wrangler I want to cat a particular sheet of an excel file not just the first one so that I can use that sheet or inspect different sheets when deciding what to do

```
data cat EXCEL-FILE
```

Just results in cat-ing of the first sheet (which is a good default).

But often first sheet is just metadata (e.g. `data cat https://www.bis.org/statistics/pp/pp_detailed.xlsx`) or i just want to see other sheets. In these cases i want to be able to specify a sheet other than the first to cat.

## Acceptance criteria

* [x] I can do `data cat https://www.bis.org/statistics/pp/pp_detailed.xlsx` and it prints the first sheet as before
* [x] I can do `data cat https://www.bis.org/statistics/pp/pp_detailed.xlsx --sheet 2` and it prints the second sheet
* [x] I can do `data cat https://www.bis.org/statistics/pp/pp_detailed.xlsx out.csv --sheet 3` and it saves the third sheet to `out.csv` file in my disk

## Tasks

* [x] refactor `File.rows()` method in `data.js` library so it accepts `sheet` argument and passes to excel parser
* [x] refactor dumpers in `datahub-client` library so they take `sheet` argument that is then passed to `File.rows()` method
* [x] refactor `/bin/data-cat.js` module in cli lib so we handle `sheet` argument passed from the user

**Comment by anuveyatsu** [comment]
FIXED and will be available with next release of the CLI tool.
