### ISSUE TITLE
[info] command should work on any type of file not just tabular

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#218]
All of the following commands should do something sensible:

```
data info my.pdf
data info my.xls
data info abc.xx
```

The original issue was moved to https://github.com/datahq/data-cli/issues/287

## Acceptance criteria

* [x] I can run `data info my.xxx` and get file descriptor
* [x] I can run `data info my.xls` and get file descriptor + first 10 rows of the default sheet (1st)

## Tasks

* [x] refactor `data-info.js` module so it adds schema only for known tabular formats
* [x] don't try to show first 10 rows for non-tabular files as it's causing errors
* [x] add/update tests

**Comment by anuveyatsu** [comment]
FIXED and available from v0.7.9 - https://github.com/datahq/data-cli/releases/tag/v0.7.9

**Comment by rufuspollock** [comment]
@anuveyatsu when fixing could you give some example output of e.g. `data info my.xls` 😄
