### ISSUE TITLE
Refactor get command

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#22]
The outcome of the discussion with @rufuspollock :

Suggestion 1:

> Should use async everywhere you can (esp when handling data)

Suggestion 2:

> * Different semantics around {data}
     * => very different operation - e.g. need to get datapackage.json from API first to work stuff out ...
     * datapackaged.com/api/publisher/package

Suggestion 3:

> Not found or other error should write an error to the user

## Acceptance criteria

* [ ] async methods are everywhere, especially when handling data
* [ ] can get data and output to stdout by using publisher name, package name and resource name (or resource path)
* [ ] or can get to directory - write to given directory with path from resource
* [ ] can download entire data package
* [ ] throw an error if not found

## Tasks

- [x] refactor get methods to be asyn [2]
- [x] refactor url for getting the metadadata and obtain bitstore url from there [1]
- [x] stdout part of the csv file (first 30 lines?), not entire file [1]
- [x] refactor code to get data from package resource name, path (with extension), path (without extension) [3]
  - [ ] tests [1]
- [x] refactor get to be able to get whole package [3]
  - files
  - dp.json
  - readme

### Use async where possible, esp for handling data

We should exploit async feature of JS instead of trying to avoid. It is a non-blocking language which allows us to make concurrent API calls - it is useful when getting multiple resources so it is much quicker.

### Different semantics around {data}

We've been doing it wrong:

* `url` should be `/api/package/{publisher}/{package}` and base should be obtained from config file
* another crucial point is we are outputting entire content of a resource to stdout, but what if there are billions of rows..

#### Get data and print to stdout

```
# gets data from the bitstore and prints out in STDOUT
# NOTE: .ext is optional (we just ignore for now but allow user to provide)
# look up {data} as name in resource array ...
datahub get {publisher}/{package}/{data}
```

QU: what is `{data}` - i would assume it was either the file path as found in resources array OR resource name.

* {data} = resource name first (if match use it)
* {data} = resource path (if match use that)

#### Get to directory

```
datahub get {publisher}/{package}/{data[.ext]} {dest}
```

e.g. i have resource like:

```
{
  "name": "mydata",
  "format": "csv",
  "path": "data/subdir/abc.csv"
}
```

What do you do?

* dest must be a directory (if an existing file throw an error - and prompt to use without {dest} and use stdout piping)
* write to dest with path from resource

#### Get data package

We also want to support:

```bash
# this downloads the datapackage.json, README.md, resources etc
datahub get {publisher}/{package} {directory}
```

**Comment by anuveyatsu** [comment]
CLOSING for now as we have decided to use https://github.com/zeit/now-cli
