### ISSUE TITLE
Return full URL for showcase page once pushed

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#220]
Use the URL returned from specstore, which will be the full URL to showcase page.

## Acceptance criteria

* [x] once I've pushed using CLI, the full url to the specific pushed revision is copied to the clipboard

## Tasks

* [x] refactor `data-push.js`
* [x] refactor `data-push-flow.js`

## Analysis

Get revision_id from specstore response.

**Comment by Mikanebu** [comment]
FIXED, now when you successfully publish dataset, you will get the full showcase page(revision version). Release new CLI with this fixes https://github.com/datahq/datahub-cli/releases/tag/v0.6.2
