### ISSUE TITLE
Cannot find module 'escape-string-regexp'

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#226]
datahub-cli throws `Cannot find module 'escape-string-regexp'` error if you try and install with `npm install -g datahub-cli`

datahub version 0.6.1

## Acceptance Criteria 

* [x] `data --version` displays version instead of erroring 

## Tasks

* [x] find the bug 
* [x] publish latest verison on npm

**Comment by zelima** [comment]
FIXED version of CLI was not up to date on npm. fix with `0.6.3` release (though bug not identified)
