### ISSUE TITLE
Dataset URL is not copied to clipboard

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#227]
Tried to Published the file with `data push mydata`. It was successfully published but getting: 
```
Could not copy to clipboard - Couldn't find the required `xsel` binary. On Debian/Ubuntu you can install it with: sudo apt install xsel
🙌  your data is published!
🔗  https://datahub.io/zelima/old_stats-brave-dragon-82/v/4 (copied to clipboard)
```
Dataset is published successfully and I can see it on datahub, but I'm getting this "warning" and url is not actually copied 

Reproduce:

* download datahub **binary** (works fine with npm) on linux `v 0.6.3`
* try to push

## Acceptance Criteria

* [x] URL is copied to clipboard if no  error
* [x] if coping fails do not say that it is

## Tasks

* [ ] ~~reproduce with npm~~ 
* [x] add check if copping failed and if so not display that it is copied 

## Analysis

I'm afraid `xsel` is something that is required to be installed via `clipboardy` lib:  https://github.com/sindresorhus/clipboardy/blob/5c610c36d270009d1580f4cc6263a8f13c69d19c/lib/linux.js#L7

**Comment by zelima** [comment]
FIXED
