### ISSUE TITLE
data info for remote url returns invalid error message

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data-cli#228]
`data info https://datahub.io/core/finance-vix` does not work

```bash
> Error! File is not in known tabular format.
```

## Acceptance criteria

* [x] data info works fine

## Tasks

* [x] debug this error
* [ ] come up with solution

**Comment by zelima** [comment]
INVALID. This is in fact expected behaviour for now. to get info for the remote dataset URL should be for datapackage.json as described in `data help info` - correct command:
`data info https://datahub.io/core/finance-vix/datapackage.json`

Though we want this to be changed in future. Follow here https://github.com/datahq/data.js/issues/24
