### ISSUE TITLE
Display status for 'push-flow'

### ISSUE THREAD

**Issue by AcckiyGerman** [datopian/data-cli#232]
As a user I want to see the process status (or errors, if any) when doing `push-flow` so I could fix my datapackage configs if something goes wrong.

## Acceptance criteria

* [ ] User could see the `push-flow` process status and errors

## Tasks

* [ ] datahub-cli returns 'long URL' to user, so user could see the flow details
    * [ ] read datahub-cli `push-flow` method
    * [ ] make [or change] a test, relevant to the task
    * [ ] change method so it will return 'Long URL' to user
* [ ] post PR fixes and merging

## Analysis 

After data push-flow you were given with "short URL" instead of "long" (https://datahub.io/owner/dataset VS https://datahub.io/owner/dataset/v/1)
On "long" URL you could see more details from flow. and you could debug easily

**Comment by AcckiyGerman** [comment]
Was fixed in v0.6.3 by @anuveyatsu 

Example:
```bash
user@pc:~/datopian/datasets/airport-codes$ data push-flow
🙌  your data is published!
🔗  https://datahub.io/AcckiyGerman/airport-codes/v/2 (copied to clipboard)
```
