### ISSUE TITLE
Invalid error when `user id` not match with `owner id`

### ISSUE THREAD

**Issue by AcckiyGerman** [datopian/data-cli#233]
When the wrong ownerid is set in the yaml meta section I get `> Error! Cannot read property 'split' of null`
Related issue: https://github.com/datahq/datahub-cli/issues/237

As a user I want to see more informative error when trying to push the data so I could understand what to fix.

## Acceptance criteria

* [ ] change 'ownerid' in the meta section of `flow.yaml` , do `data push-flow`, get a proper informative error
* [ ] the error shows 'ownerid' value, that the program expects from the user to be set in flow.yaml

**or even better**
* [ ] if user credentials in `flow.yaml` and `config.json` are different - the program sets the proper values in a flow.yaml file after asking user about that.

**the best solution**
* [ ] there is no `ownerid` field in `flow.yaml`

## Tasks

* [ ] update method code
* [ ] update error message

## Analysis 

Error appears when you:
* got automated datapackage from github and do `data push-flow` under different user
* did a `data login` with a test api, change a credentials to other user and now trying to `data push-flow`

Q: Why do we need the `ownerid` field in flow.yaml, if the program had already got it it from `config.json` ???

Q: If we want to keep the original ownership, why to check if `user.id == owner.id` and only then pushing? It is not a protection, anyway.

**Comment by AcckiyGerman** [comment]
## Analyse update

https://github.com/datahq/data-cli/blob/a0eb8458feb8cec5c0d62b2f676a7ecf0b939a0e/bin/data-push.js#L90

```javascript
const datahubConfigs = {
      apiUrl: config.get('api'),
      token: config.get('token'),
      debug: argv.debug,
      ownerid: config.get('profile') ? config.get('profile').id : config.get('id'),
      owner: config.get('profile') ? config.get('profile').username : config.get('username')
    }
```
I tried to provide the `ownerid` from some other user and I've got 'UNAUTHORISED' response from the server, so it looks like the server is secured.

Question is why do we set `ownerid` and `owner` on the client side, if this info could be inferred on the server-side (and it does when do security check).

**P.S.** This guessing `where is the 'id'`:
```
ownerid: config.get('profile') ? config.get('profile').id : config.get('id'),
owner: config.get('profile') ? config.get('profile').username : config.get('username')
```
seems to be done to keep the backwards compatibility, but now I think it is redundunt

**Comment by zelima** [comment]
WONTIFX. push-flow is depreciated
