### ISSUE TITLE
Wrong links from 'data push' when using test api

### ISSUE THREAD

**Issue by AcckiyGerman** [datopian/data-cli#234]
As a product owner I don't want hardcoded addresses in my programs, so I won't have troubles when moving site to other domain, sell the product to other company, etc

As a developer I want to get right links when testing the datahub-cli, so I don't need to guess, where actually my datapackage is placed.

## Acceptance criteria

* [ ] `data push --api https://api-testing.datahub.io` returns right link (now https://testing.datahub.io/...) to the uploaded dataset
* [ ] `data push-flow --api https://api-testing.datahub.io` returns right link 

## Tasks

* [ ] add tests for `data push`, `data push-flow`
* [ ] fix the method which creates link, so link is created with actual domain name

## Analysis

When I used test API, I've got links like https://datahub.io/AcckiyGerman/airport-codes/v/7 , but the correct address is https://testing.datahub.io/AcckiyGerman/airport-codes/v/7 (the domain name is wrong) 
Seems that domain name is hardcoded somewhere in the datahub-cli.

**Comment by anuveyatsu** [comment]
WONTFIX - this is too minor atm so closing it as wontfix. Please, reopen if you find it important.
