### ISSUE TITLE
Make automation to grab readme.md file.

### ISSUE THREAD

**Issue by AcckiyGerman** [datopian/data-cli#236]
As a automation user I want to use existing resources and files so I reduce the amount of manual work.

## Acceptance criteria

* [ ] `dataset/.datahub/readme.md` or `dataset/readme.md` (letters case does not matters) is used automatically for result dataset  

or
* [ ] user can link the readme file in `.datahub/flow.yaml` (better with relative link)

## Task 

* [ ] make test
* [ ] implement method
* [ ] update automation docs

## Analysis

ATM when you preparing the automation you need to write the whole readme file in one raw string with `\n \t` etc. It is uncomfortable and the readme file is usually already exists in the data-package that we are trying to automate.
