### ISSUE TITLE
Invalid error from "data push-flow"

### ISSUE THREAD

**Issue by AcckiyGerman** [datopian/data-cli#237]
As a user, I want to see readable errors, so I could fix my configs.
Related issue: https://github.com/datahq/datahub-cli/issues/233

## Acceptance criteria
Clone one of automated datasets, and make several mistakes:

#### invalid `meta` section
> actually, if you are not a `core` user - you should get this error without any efforts :)

Change `ownerid` to `invalid_id`. Then do `data push-flow`.
* [ ] you should get a readable error, and can understand, that something wrong with credentials.

Fix `ownerid` paramether

#### invalid `schedule`
Change `schedule: every 1d` to `schedule: each time when I'm drunk`
Then do `data push-flow`.
* [ ] you got error like `Bad time unit for schedule...` and could understand it

Fix `schedule` section.

#### invalid data schema
Remove or add any field in a source schema. Do `data push-flow`
* [ ] you should get something like `> Error! validation failed for contents`

## Tasks

* [ ] make tests
* [ ] fix error returning method

## Analysis

Each time when I do `data push-flow` and there are any error in a configs - I got only this `> Error! Cannot read property 'split' of null`  
But if I run `data push-flow --debug` - I could see some error.
![image](https://user-images.githubusercontent.com/11707682/34602964-41c8fcb6-f202-11e7-8060-6468432a0421.png)

My conclusion is that the error is lost somewhere on the way to user and this should be easy to fix.

Related issue: https://github.com/datahq/datahub-cli/issues/233

**Comment by zelima** [comment]
WONTFIX/OBSOLETE. `push-flow` is now deprecated
