### ISSUE TITLE
Rename repo to data-cli from datahub-cli

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#247]
Rename repo to data-cli from datahub-cli reflecting its actual name and purpose.

## Acceptance criteria

* [x] datahub-cli renamed to data-cli
* [x] published to npm

## Tasks

* [x] Change repo on github
* [x] Change name in package.json and README
* [x] Push to npm

**Comment by Mikanebu** [comment]
FIXED, new release on npm v0.6.5 https://www.npmjs.com/package/data-cli
