### ISSUE TITLE
[Push] pushing valid dataset with the path to datapackage.json fails

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#252]
`data push path/to/datapackage.json` failes with following 

```
> Error! ENOTDIR: not a directory, stat '/home/zelima/datopian/datahq/qa-tests/data-files/csv/datapackage.json/comma-separated.csv'"
```

## Acceptance Criteria

* [x] `data push path/to/datapackage.json` pushes dataset to datahub

## Tasks

* [x] add failing test
* [x] see the source and debug
* [x] pass the tests

**Comment by AcckiyGerman** [comment]
FIXED: Cannot reproduce the bug in `data` v0.6.7
TESTED by @zelima @Mikanebu @acckiygerman
datahub-qa reference is closed: https://github.com/datahq/datahub-qa/issues/64
