### ISSUE TITLE
Cannot push tabular data with values that have double quotes

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data-cli#253]
### Steps to reproduce 

* take the following data file - https://github.com/frictionlessdata/test-data/blob/master/files/csv/all-schema-types.csv
* push it using "data push ..."

### Output

got error "Invalid opening quote" - this is because we need to have escape character setup

## Acceptance criteria

* [x] generated schema should have appropriate data type per field
* [x] showcase page should succeed and work as expected

## Tasks

* [x] analysis - see discussion here https://github.com/datahq/datahub-qa/issues/66
* [x] include double quotes as escape character in the "dialect" in "descriptor" [data.js]
* [x] include double quotes as tabulator argument in the flow spec [datahub-client]

**Comment by anuveyatsu** [comment]
FIXED - will be available in the next release of the CLI v0.7.1
