### ISSUE TITLE
Pushing large files is not working

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#255]
Pushing a file with > 1024 columns even did not show spinner, just stopped.
Sample data is here https://github.com/frictionlessdata/test-data/blob/master/data-files/csv/1030_columns.csv

Pushing large csv:
- `data push` doesn't push 168mb sample, just exit with no error
- `data push` seems working fine, but it is taking a huge time for publishing
* [x] Showcase page fails (Literally crashes the browser tab)  when trying to create a data preview for big (168mb) table: https://github.com/datahq/frontend/issues/198

## Acceptance criteria

* [x] I can push https://github.com/frictionlessdata/test-data/blob/master/data-files/csv/1030_columns.csv 
* [x] I can push large files, eg, 168MB

## Tasks

* [x] investigate/analyse the source of the issue
    * [x] create new tasks here

* [x] first reported here: https://github.com/datahq/datahub-qa/issues/62 

#### 1030_columns error
Error happens in the `data.js` module:
```javascript
async addSchema() {
    // Ensure file is tabular
    if (knownTabularFormats.indexOf(this.descriptor.format) === -1) {
      throw new Error('File is not in known tabular format.')
    }
    const stream = await this.stream()
    this.descriptor.schema = await infer(stream)  // HERE IT FAIL WITHOUT ERRORS
  }
```
Here is a bug reproducing code: https://runkit.com/acckiygerman/5a742cdbce9f1b0012db4907

~~I fixed it by passing `file.path` to `tableschema.infer()` instead of passing stream (tableschema don't need  the stream - it creates stream from the path|url by itself )~~  Other programmer had fixed this, see the update

### Update:
The issue was already reported and fixed in this PR https://github.com/frictionlessdata/tableschema-js/pull/118 by some Italian guy.
@acckiygerman and @anuveyatsu tested it with wide (10000 columns) and big (168mb) files - the `data push` works fast and uploads data successfully. 
Now merging this PR..

Now another bug appears, when pushing big files:
* [ ] Showcase page fails (Literally crashes the browser tab)  when trying to create a data preview for user:
https://datahub.io/AcckiyGerman/big-168-wide-10000/v/1

### Update 5 feb

https://github.com/frictionlessdata/tableschema-js/pull/118 is merged, BUT seems some STREAM error is still there.
I updated `tableschema`, `data.js` and `data-cli` and linked them, but still have problems with pushing files:
- cannot push data with a lot of columns ( >= 2000 )  program crashed
- cannot push (5000row X 1000 columns) 80mb table  - program crashed

**Comment by AcckiyGerman** [comment]
Closed because is duplicated.

**Comment by AcckiyGerman** [comment]
The error happens in the `data.js` module:
```javascript
const stream = await file.stream()
file.descriptor.schema = await tableschema.infer(stream)  // here error happens
```
Here is a bug reproducing code: https://runkit.com/acckiygerman/5a742cdbce9f1b0012db4907
I'll try to fix it by spliting stream into chunks

**Comment by zelima** [comment]
@AcckiyGerman Please move this comment in "Analysis" section of the original issue description

**Comment by AcckiyGerman** [comment]
Update:
The issue was already reported and fixed in this PR https://github.com/frictionlessdata/tableschema-js/pull/118 by some Italian guy.
@acckiygerman and @anuveyatsu tested it with wide (10000 columns) and big (168mb) files - the `data push` works fast and uploads data successfully. 
Now merging this PR..

Now another bug appears, when pushing big files:
* [ ] Showcase page fails (Literally crashes the browser tab)  when trying to create a data preview for user:
https://datahub.io/AcckiyGerman/big-168-wide-10000/v/1

**Comment by AcckiyGerman** [comment]
frictionlessdata/tableschema-js#118 is merged, BUT seems some STREAM error is still there.
I updated tableschema, data.js and data-cli and linked them, but still have problems with pushing files:

- cannot push data with a lot of columns ( >= 2000 ) program crashed
- cannot push (5000row X 1000 columns) 80mb table - program crashed

@anuveyatsu can you please test the latest fix on your machine ?

**Comment by AcckiyGerman** [comment]
TESTED: by @anuveyatsu with last tableschema fix and working!

**Comment by zelima** [comment]
@AcckiyGerman if this is tested and working, please tick appropriate items from checklist above and close

**Comment by AcckiyGerman** [comment]
I will close soon, when we release fixed `data-cli`

**Comment by AcckiyGerman** [comment]
FIXED: 
Tested and working in the last version of `data-cli`

**Comment by AcckiyGerman** [comment]
Retested again and FAIL :sob: 
```shell
user@pc:~/work/frictionlessdata/test-data$ data push files/csv/1030_columns.csv 
user@pc:~/work/frictionlessdata/test-data$ data -v
0.7.1
user@pc:~/work/frictionlessdata/test-data$ data push files/csv/1030_columns.csv 
user@pc:~/work/frictionlessdata/test-data$ data push files/csv/1030_columns.csv 
user@pc:~/work/frictionlessdata/test-data$ node /home/user/work/datahq/data-cli/bin/data.js push files/csv/1030_columns.csv 
user@pc:~/work/frictionlessdata/test-data$ 
```
`data push` just crashing without warnings or errors again (((

**Comment by anuveyatsu** [comment]
@AcckiyGerman this should be working now starting from data-cli@0.7.3 - https://github.com/datahq/data-cli/releases/tag/v0.7.3

**Comment by AcckiyGerman** [comment]
re-TEST: OK
FIXED

**Comment by Mikanebu** [comment]
@anuveyatsu Tried to push ~350Mb file but getting this error
```
Meirans-MBP:test-data Zhiyenbayev_mirza$ data push files/csv/big.csv 

<--- Last few GCs --->

[88514:0x103000000]   181084 ms: Mark-sweep 1407.7 (1456.0) -> 1407.7 (1439.0) MB, 491.3 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 491 ms) last resort GC in old space requested
[88514:0x103000000]   181753 ms: Mark-sweep 1407.7 (1439.0) -> 1407.7 (1439.0) MB, 669.8 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x24501e0a5ee1 <JSObject>
    1: guessDelimiter [/Users/Zhiyenbayev_mirza/Desktop/Datopian/src/data-cli/node_modules/csv-sniffer/index.js:~274] [pc=0x120c94d38870](this=0x2450f900be31 <JSGlobal Object>,sample=0x2450ff502201 <Very long string[251055548]>,newlineStr=0x245087dacdf9 <String[2]\: \r\n>,delimiters=0x2450a2877399 <JSArray[8]>)
    3: /* anonymous */ [/Users/Zhiyenbayev_mirza/Desktop/Datopian/src/data-cli/node_m...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/local/bin/node]
 5: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 6: 0x120c94b8463d
 7: 0x120c94d38870
Abort trap: 6
```

**Comment by zelima** [comment]
@anuveyatsu seems like `csv-sniffer` loading whole data into memory. can we limit that somehow?

**Comment by AcckiyGerman** [comment]
Should we reopen this issue, until fixing it @zelima ?

**Comment by zelima** [comment]
@AcckiyGerman yes

**Comment by anuveyatsu** [comment]
FIXED and will be available with the next release of the CLI tool.
