### ISSUE TITLE
[Push] Pushing remote data package should fail with error

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#256]
If you try and push remote package (with URL to datapackage.json) it will be treated as a remote file and will be pushed as non-tabular HTML file.
```
data push https://github.com/frictionlessdata/test-data/blob/master/datapackages/remote-csv/datapackage.json
```

We need to detect this and display to user that we can only push local files for now.

## Acceptance Criteria

* [x] Running above command displays the following: `Not able to push remote package`

## Tasks 

* [x] detect if is URL and ends with datapackage.json 
* [x] display error message
* [ ] tests

**Comment by zelima** [comment]
FIXED
