### ISSUE TITLE
Cannot push empty files or zero byte files

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#257]
Sample data can be found here https://github.com/frictionlessdata/test-data/tree/master/files/empty-files and here https://github.com/frictionlessdata/test-data/tree/master/files/zero-files

When pushing getting following errors:

> Error! Cannot calculate proper length in a synchronous way.
> OR program hang with empty.csv
> for all other extensions - throws error: Cannot calculate proper length in a synchronous way.

## Acceptance criteria

* ~~[ ] I am able to push empty files from https://github.com/frictionlessdata/test-data/tree/master/files/empty-files and from here https://github.com/frictionlessdata/test-data/tree/master/files/zero-files~~
* ~~[ ] showcase page tells me that file is empty~~

* [x] show proper error, when trying to push empty file

## Tasks

* [x] investigate/analyse the source of the issue (in QA: datahq/datahub-qa#60)
* [ ] create tests
* fix error messages
   - [x] for tabular data
   - [x] for not tabular https://github.com/datahq/datahub-client/pull/18

## Analysis for the client side (data-cli)  (updated by Dima)

- Tabular files cause error in CSVSniffer
- Not-Tabular files cause error in FormData.getLengthSync 
- empty.xls cause program hung during pushing.

#### empty (no extention), empty.txt, zero, zero.html, zero.json, zero.txt zero.xls
```shell
Error: Cannot calculate proper length in synchronous way.
    at FormData.getLengthSync (/home/user/work/datahq/data-cli/node_modules/form-data/lib/form_data.js:344:17)
    at resources.map (/home/user/work/datahq/data-cli/node_modules/datahub-client/lib/utils/datahub.js:69:36)
    at Array.map (<anonymous>)
    at DataHub.push (/home/user/work/datahq/data-cli/node_modules/datahub-client/lib/utils/datahub.js:55:31)
```

#### empty.csv, zero.csv
```shell
Error: No newline characters found in your file...
    at CSVSniffer.sniff (/home/user/work/datahq/data-cli/node_modules/csv-sniffer/index.js:631:10)
    at guessParseOptions (/home/user/work/datahq/data-cli/node_modules/data.js/lib/parser/csv.js:16:27)
```

#### empty.html  &  empty.json
Uploaded. Showcase page not shows any error.

#### empty.xls
```shell
$ data push empty.xls --debug
.....
> [debug] Uploads to rawstore: Complete
> [debug] Uploading to source spec store
> [debug] Getting authz token for rawstore 
# the program hung consuming 100% of CPU at this point
```
This should be fixed here: https://github.com/datahq/datahub-qa/issues/58

# Analysis update 2 march
@zelima @anuveyatsu Seems I found the `zero-files` issue.
I've added some logging to uploads function in `datahub-client`:
```node
let totalLength
try {
        totalLength = formData.getLengthSync()
        console.log(`resource: ${resource.path}`)
        console.log(`encoding: ${resource.encoding}`)
        console.log('length:', totalLength)
```
And it appears that `0 bytes files` are not `0` any more :sunglasses: 
```
data.js push test/fixtures/test-data/files/zero-files/zero.txt --name zero-test
resource: test/fixtures/test-data/files/zero-files/zero.txt
encoding: UTF-8
length: 1931       ## <<<<<<<<<<<<<<<<<<<<<
```

And then I remembered, that last thing I fixed was processing `non-utf8` encoding files..
So I realized, now, when the file is empty, we try to guess its encoding, but
- `chardet.detectFileSync(this.path)` returns `undefined`
- then `File.stream()` returns `fs.createReadStream(this.path).pipe(iconv.decodeStream(this.encoding))` stream, decoded by `iconv` lib with `encoding=undefined`
- and this decoded Stream is not `0` bytes length any more

Although, pushing such `non-really-zero` stream-encoded `zero-file` goes well, and on the rawstore an empty file appears, and it showed as empty file on the frontend: 
https://datahub.io/AcckiyGerman/zero-test
You can download this `zero.txt` and it has `0 bytes length` as it should be.

So the question remains: Should we allow user to upload empty files?  @anuveyatsu WDYT

## error when pushing `iso8859.csv` still remains and this is a related issue
```
data.js push test/fixtures/test-data/files/csv/encodings/iso8859.csv --name encoding-test
resource: test/fixtures/test-data/files/csv/encodings/iso8859.csv
encoding: ISO-8859-1
length: 2102
------------------------------
> Error! Error uploading to rawstore for iso8859.csv with code 400 reason <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MalformedPOSTRequest</Code><Message>The body of your POST request is not well-formed multipart/form-data.</Message><RequestId>9898988F8930B6B2</RequestId><HostId>LfYU/vVSX2H2do+58z31vKz1Dh/zD1/8X3L7TGYvBMmj6ccod2aSB/aaSz1wui9/uJaohYlkYps=</HostId></Error>
```
If I roll back the `data.js` repo before `non-UTF8` commit:
- non-utf8 can be pushed,
- frontend shows right characters e.g. `Réunion`
- `data cat iso8859` shows wrong characters in the terminal

## So `iconv` Encoded non-utf8 stream:
- is valid for printing to terminal
- is not valid for uploading to the current rawstore API

**Comment by AcckiyGerman** [comment]
Mirror issue in QA: https://github.com/datahq/datahub-qa/issues/60

**Comment by AcckiyGerman** [comment]
We decided to change the acceptance criteria, instead of pushing empty files the program will stop with the warning.

**Comment by AcckiyGerman** [comment]
https://github.com/datahq/data-cli/pull/281

**Comment by zelima** [comment]
@AcckiyGerman tip: There's no need of pasting the PR links as a separate comment, especially without saying anything. Github references them when you mention in PR description or commit messages - if you take a look, it's right above your comment

**Comment by AcckiyGerman** [comment]
Thanks!

**Comment by AcckiyGerman** [comment]
FIXED:
When trying to push empty tabular file user will see an Error.
zero-length non-tabular file will show another error (fixed in `datahub-client`)

**Comment by AcckiyGerman** [comment]
Issue is again here: https://github.com/datahq/datahub-qa/issues/60#issuecomment-369561858
Now we can push empty files via `FormData` npm lib, and so user get no error message.

Need to investigate why, probably `form-data` was updated and they fixed old issue.

**Comment by Mikanebu** [comment]
@AcckiyGerman This issue is not resolved, it is not fully satisfied test criteria
* allowed pushing empty file without extension
* allowed pushing `txt` file
* 0 bytes files

**Comment by AcckiyGerman** [comment]
@Mikanebu 
At the beggining this issue was **Cannot push empty files or zero byte files**
- The reason was that FormData lib returned an error for zero-files
- we decided not to push empty files AND changed the **Acceptance criteria**
- So I changed the program to catch exception from FormData and show `Error: you cannot push empty data`

Now (and this is just my assuming, that need to be checked)
- FormData does not throw exception on zero-files
- data-cli does not catch it
- zero-files are uploading WELL

If my Assuming is right, and the problem is in the missed exception from the `form-data` lib,
I see two solutions:
- change the **Acceptance criteria** and Allow user to push empty and zero files
- check file size before pushing and throw `Error: you cannot push empty files`

**Comment by zelima** [comment]
@AcckiyGerman I would discuss this together with @anuveyatsu - what should we do with empty files in frontend? How should we treat? What may it brake? 

Think this needs some good analysis before switching acceptance criteria. Eg we are reading filesize at some point in the code anyway. We could use that info to check if it's zero.

But my voice is for letting people pushing empty files. (Also probably we should think about `get`?)

**Comment by AcckiyGerman** [comment]
@zelima @anuveyatsu Seems I found the `zero-files` issue.
I've added some logging to uploads function in `datahub-client`:
```node
let totalLength
try {
        totalLength = formData.getLengthSync()
        console.log(`resource: ${resource.path}`)
        console.log(`encoding: ${resource.encoding}`)
        console.log('length:', totalLength)
```
And it appears that `0 bytes files` are not `0` any more :sunglasses: 
```
data.js push test/fixtures/test-data/files/zero-files/zero.txt --name zero-test
resource: test/fixtures/test-data/files/zero-files/zero.txt
encoding: UTF-8
length: 1931       ## <<<<<<<<<<<<<<<<<<<<<
```

And then I remembered, that last thing I fixed was processing `non-utf8` encoding files..
So I realized, now, when the file is empty, we try to guess its encoding, but
- `chardet.detectFileSync(this.path)` returns `undefined`
- then `File.stream()` returns `fs.createReadStream(this.path).pipe(iconv.decodeStream(this.encoding))` stream, decoded by `iconv` lib with `encoding=undefined`
- and this decoded Stream is not `0` bytes length any more

Although, pushing such `non-really-zero` stream-encoded `zero-file` goes well, and on the rawstore an empty file appears, and it showed as empty file on the frontend: 
https://datahub.io/AcckiyGerman/zero-test
You can download this `zero.txt` and it has `0 bytes length` as it should be.

So the question remains: Should we allow user to upload empty files?  @anuveyatsu WDYT

## error when pushing `iso8859.csv` still remains and this is a related issue
```
data.js push test/fixtures/test-data/files/csv/encodings/iso8859.csv --name encoding-test
resource: test/fixtures/test-data/files/csv/encodings/iso8859.csv
encoding: ISO-8859-1
length: 2102
------------------------------
> Error! Error uploading to rawstore for iso8859.csv with code 400 reason <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>MalformedPOSTRequest</Code><Message>The body of your POST request is not well-formed multipart/form-data.</Message><RequestId>9898988F8930B6B2</RequestId><HostId>LfYU/vVSX2H2do+58z31vKz1Dh/zD1/8X3L7TGYvBMmj6ccod2aSB/aaSz1wui9/uJaohYlkYps=</HostId></Error>
```
If I roll back the `data.js` repo before `non-UTF8` commit:
- non-utf8 can be pushed,
- frontend shows right characters e.g. `Réunion`
- `data cat iso8859` shows wrong characters in the terminal

## So `iconv` Encoded non-utf8 stream:
- is valid for printing to terminal
- is not valid for uploading to the current rawstore API

**Comment by anuveyatsu** [comment]
This will be fixed once https://github.com/datahq/data.js/pull/43 merged and new release of the CLI is released.

**Comment by AcckiyGerman** [comment]
FIXED: https://github.com/datahq/data.js/pull/43
We do not decode File.stream() with `iconv` in `data.js` any more.
`Iconv` used only in `csv parser` for correct `data cat non-utf8.csv`

Now when user push empty file, he will see
```
> Error! > You can not push empty files, please add some data and try again:
test/fixtures/test-data/files/empty-files/empty.txt
```
