### ISSUE TITLE
[Push] Pushing excel file with non existing sheets should fail

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#258]
Reported here: https://github.com/datahq/datahub-qa/issues/50

Currently, if you try and push excel file and define non-existing sheet it will not fail and push data from the first sheet of excel file.
Another problem is that if you select even existing sheet, it'd push the first one, which means we're not able to push a sheet other than first one.

## Reproduce

Try to push excel file with 2 sheets named `sheet1` and `sheet2`. The following command will push the data from the first sheet

* run `data push myexcel.xlsx --sheets=3`
* run `data push myexcel.xlsx --sheets=2`
* run `data push myexcel.xlsx --sheets=1,2`
* run `data push myexcel.xlsx --sheets=all`

## Acceptance 

* [x] We want to detect if sheet does not exist and say this to user

## Tasks

* [x] Do analysis
* [x] refactor to detect non existing sheet
* [x] refactor to throw error when name instead of index is provided

**Comment by AcckiyGerman** [comment]
**Pushing excel data by the sheet name** - https://github.com/datahq/datahub-qa/issues/88

**Comment by AcckiyGerman** [comment]
FIXED.
If an empty sheet is pointed by user, the program will reply with `> Error! You cannot push an empty sheet. Please, add some data and try again.`
