### ISSUE TITLE
Ensure npm/yarn installable

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#263]
@anuveyatsu commented on [Fri Jan 26 2018](https://github.com/datahq/pm/issues/108)

We expect a lot of people to install the CLI tool using package managers such as npm/yarn. To provide them a nice experience we want to double check if everything works.

Notice, package name was changed recently, now it's called `data-cli` - check docs, blog posts and any other writings and update instructions.

## Accpetance criteria

* [x] data CLI tool is published in the NPM here http://npmjs.com/package/data-cli
  * [x] it has clear README about installation so I just copy paste it and run `data help` and it works
* [x] I can install and start using data CLI tool with npm/yarn

## Tasks

* [x] install and play with the tool using npm and yarn
  * [x] do I have to use `-g` flag - if so update README so it is very clear
* [x] try out on another OS, e.g., Linux
* [x] update docs, blog post and other writings/instructions with a new name `data-cli` (old one was `datahub-cli`)

**Comment by zelima** [comment]
DUPLICATE of https://github.com/datahq/data-cli/issues/263
