### ISSUE TITLE
Research data CLI app size reduction

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#264]
@anuveyatsu commented on [Fri Jan 26 2018](https://github.com/datahq/pm/issues/107)

Currently, our CLI app is 123MB - https://github.com/datahq/data-cli/releases/tag/v0.6.5
This is too large and may be crucial for some users wanting to download it. We want it to be at least below 100MB (this seems a break point for majority).

## Acceptance criteria

* [x] CLI app's size is below 100MB

## Tasks

* [x] Research existing issues on github to see who else facing similar problem and find possible solutions [1h]
* [x] Experiment with available options [2h]
* [x] Select the best option and apply it in production (release) [0.5h]

## Analysis

This problem is discussed here - https://github.com/zeit/pkg/issues/50

Options:

* Try xz compression
* Apply prepack + uglify before packaging
* Use https://github.com/upx/upx to reduce the size
  * wrapper https://github.com/roccomuso/upx
