### ISSUE TITLE
Show proper error when there are invalid path in the `dp.json`

### ISSUE THREAD

**Issue by AcckiyGerman** [datopian/data-cli#265]
As a user I want to see a readable error when I push the data, so I could fix my dataset

## Acceptance criteria

* [x] user got an error when tries to `data push dp.json` with `../` in the `resources.path`
    - [x] `the path of <name> resource is invalid`   OR
    - [x] `using backwards "../" in the path is prohibited due to security reasons`
* [x] user got an error when there is NO file on the given path
   - [ ] `the path of <name> resource is invalid`   OR
   - [x] `file not found on path <path>`

## Tasks

* [ ] write tests (use https://github.com/frictionlessdata/test-data/packages/ ...invalid packages)
    - ~~missed file~~ the feature is already exists.
    - ~~invalid URL~~ we will not test this when pushing dataset.
    - [ ] `../` in the `path`
* [ ] implement `check(path)` method, that runs before pushing
* [x] throw proper errors

## Analysis

1. missed remote file:
`data push` pushes a dataset with invalid `resource.path` URL (no any file on the URL) but then the frontend shows `Not Found for url:` error.

2. missed local file:
~~`data push` pushes a dataset with invalid `resource.path` (no file on the given path)  but then the frontend shows `Not Found for url:` error.~~
`data push` shows an error `no such file or directory` - so this one match EXPECTED BEHAVIOR

3. backward `../` in the path
    - `data push dp.json` shows `Error: [object Promise]` 
    - `data push dp.json --debug` shows
```shell
> [debug] Getting authz token for source service
> Error! [object Promise]
```
Exception happens on the spec store side @acckiygerman

### Update 10feb
Error happened in specstore, but didn't return to the user. This has been fixed in 
https://github.com/datahq/specstore/commit/fde06cdbbc223b7f33dcae7d4787af439383ea33
and now user will see errors about unsafe `resource.path`

### Solution
I think we could check that all resources exist before the push.

I want to implement checkResource[s]Availability method, which will do series of tests for:

- File
   - file exist
   - path not includes ../ (not sure about that, but)
- URL
    - I could fetch file headers and 200 <= response.status_code <= 204

Also it will throw proper error messages.

The point is to check descriptor.resources before pushing.
I'm gonna use this method in data-cli/bin/data-push.js, but implement it in the Dataset class (as resources is a part of the dataset).

**Comment by AcckiyGerman** [comment]
@anuveyatsu 
I want to implement `checkResource[s]Availability` method, which will do series of tests for:
* File
    - file exist
    - path not includes `../` (not sure about that, but)
* URL
    - I could fetch file headers and `200 <= response.status_code <= 204`

Also it will throw proper error messages.

The point is to check `descriptor.resources` before pushing.
I'm gonna use this method in `data-cli/bin/data-push.js`, but implement it in the `Dataset` class (as resources is a part of the dataset).

WDYT ?

**Comment by anuveyatsu** [comment]
@AcckiyGerman not sure about it. We also have `validate` command that reads resources and validates against the schema (for tabular ones). I am not sure if checking resources feature is really needed..

**Comment by AcckiyGerman** [comment]
Are you proposing doing data validate before every push automatically?

**Comment by anuveyatsu** [comment]
@AcckiyGerman so this issue is about unreadable error messages when you have a resource with an invalid path. As a publisher, all you need to know is that the path is wrong so you need to double check it. I know that it used to return `Error: [object Promise]` error but I think it now returns more readable message since I've refactored throwing errors behaviour today in the datahub-client library.

So you don't really need to validate before pushing - but if during the push process the CLI would try to read your resources and throw errors if something is wrong.

**Comment by AcckiyGerman** [comment]
Please read the analysis carefully - data-cli doesn't return any error when
pushing resources with invalid path. It just says - 'pushed successfully'.

"File not found" Error then shown on the frontend.

**Comment by anuveyatsu** [comment]
@AcckiyGerman I see now. I think we can check if a local path exists in `File` class in `data.js` library. E.g., in the `load` method somewhere in the following line:

https://github.com/datahq/data.js/blob/master/lib/index.js#L47

But I don't really think we should check URLs...

**Comment by anuveyatsu** [comment]
@AcckiyGerman just checked why CLI doesn't throw errors when local path is invalid. In your example, the descriptor tells that path is remote: https://github.com/frictionlessdata/test-data/blob/master/packages/invalid-local-path/datapackage.json#L6 and this is the reason it is pushing without any errors. Otherwise, it would try to get size of the file and `fs` module would throw an exception here: https://github.com/datahq/data.js/blob/master/lib/index.js#L116

**Comment by AcckiyGerman** [comment]
`data push` dataset with unsecured `resource.path` caused validation error in the specstore, but error wasn't returned to the user. This has been fixed in
https://github.com/datahq/specstore/commit/fde06cdbbc223b7f33dcae7d4787af439383ea33

Now user see:
```
> Error! Unexpected error: Local path "../../files/csv/separators/comma.csv" is not safe
```

**Comment by AcckiyGerman** [comment]
FIXED
Missed file:
```shell
invalid-local-path$ data push
> Error! ENOENT: no such file or directory, open '/home/user/work/frictionlessdata/test-data/packages/invalid-local-path/no-such-file.csv'
> You can run:
> 'data validate' to check your data.
> 'data init' to create a datapackage.
> 'data help push' to get more info.
```
Insecure path
```shell
invalid-backward-path$ data push --api http://api-testing.datahub.io
> Error! Unexpected error: Local path "../../files/csv/separators/comma.csv" is not safe
```

Invalid URL:
- we decided not to check `if the url exists` inside the `data-cli` when pushing.
