### ISSUE TITLE
data get command does not work for datasets on DataHub and GitHub

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data-cli#266]
The issue is reported here datahq/datahub-qa#43

Currently, data get acquires the html page for a dataset, not the entire dataset

## Acceptance criteria

* [x] data get {GitHub} or {DataHub} url works fine

## Tasks

* [x] refactor data-get command
* [x] add test cases
* [x] fix and test

## Analysis

data get does not work for any other users except core
tried to run data get http://datahub.io/Mikanebu/push-speed-62-1mb

invalid json response body at http://pkgstore.datahub.io/Mikanebu/push-speed-62-1mb/latest/datapackage.json reason: Unexpected token < in JSON at position 0
The reason: if you take a look on pkg url, it uses username, but it should use userid

The solution: We need to call resolver API to get userid and pass it further

**Comment by Mikanebu** [comment]
FIXED, now `data get` dataset from DataHub and GitHub works fine. Related commit to `data.js`  https://github.com/datahq/data.js/commit/221417a3a9fea87ddc2230a48ad0a8f40d8c1dc9 for getting path for fileRemote, it should not join full url with base path

**Comment by Mikanebu** [comment]
data get does not work for any other users except core
tried to run `data get http://datahub.io/Mikanebu/push-speed-62-1mb` 
```
invalid json response body at http://pkgstore.datahub.io/Mikanebu/push-speed-62-1mb/latest/datapackage.json reason: Unexpected token < in JSON at position 0
```
The reason: if you take a look on pkg url, it uses username, but it should use userid

The solution: We need to call `resolver` API to get `userid` and pass it further

**Comment by Mikanebu** [comment]
FIXED in https://github.com/datahq/data.js/pull/28. Will be available in the next `data-cli` release
