### ISSUE TITLE
Cannot update data-cli (binary)

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#269]
At the moment, if I'm using data-cli tool using executable binary, I cannot update it to a newer version. This is only possible with data-desktop right now.

User story: As a Publisher I want to update my current data-cli tool with single command so I can get the latest version quickly and use it.

## Acceptance criteria

* [ ] I can update my data-cli by runnin `data update`

## Tasks

* [x] analyse possible solutions and estimate how much of work it requires
* [ ] create set of tasks here

**Comment by anuveyatsu** [comment]
After discussion, we have decided that updating the binary itself would take too much of extra work and therefore we don't want to implement it. Instead, we'll have a clear notification when a new version is available with instructions on how to the update.

Closing as WONTFIX.
