### ISSUE TITLE
[validate] doesn't work with remote datasets

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#270]
If I try to validate a remote dataset, I would get following error:

```
> Error! ENOENT: no such file or directory, lstat
```

https://github.com/datahq/datahub-qa/issues/99

## Acceptance criteria

* [x] I run `data validate https://raw.githubusercontent.com/frictionlessdata/test-data/master/packages/different-separators/datapackage.json` and it tells me the package is valid
* [x] I run `data validate https://raw.githubusercontent.com/frictionlessdata/test-data/master/packages/types-formats-and-constraints/constraints/datapackage.json` and it throws errors as in the readme of the package

## Tasks

* [x] investigate the source of the issue
* [x] refactor cli and client libs to use `data.js` library so we have the standard way of processing a dataset identifier

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datahq/data-cli/releases/tag/v0.7.4
