### ISSUE TITLE
Automate npm/yarn installation test of the CLI tool

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#274]
As described in https://github.com/datahq/datahub-qa/issues/91 we want to install data-cli using npm/yarn and test with basic commands after each deployment.

## Acceptance criteria

* [x] Travis runs installation of data-cli using npm and yarn after each deployment

## Tasks

* [x] refactor `.travis.yml` to run script for installation of data-cli after each deployment
* [x] create shell script

## Analysis

We want to run the CLI installation script only when a new release is issued so this should go somewhere in the `after_deploy` script in the travis configs. Also, we want to test it on Linux + MacOS and using Node versions 7, 8 and 9. Still, all tests should be run as before using only Linux and node8.

```
language: node_js
matrix:
  include:
  - os: linux
    node_js: '8'
    env: TEST=true
    sudo: required
  - os: linux
    node_js:
      - '7'
      - '9
    env: TEST=false
    sudo: required
  - os: osx
    node_js:
      - '7'
      - '8'
      - '9'
    env: TEST=false
install: if $TEST; then npm install; else echo 'skipping this script...'; fi
script: if $TEST; then npm test; else echo 'skipping this script...'; fi
before_deploy: npm run pack
deploy:
  ...
after_deploy:
  - chmod ugo+x test-script.sh
  - ./test-script.sh
```

The `test-script.sh` should look like:

```bash
#!/bin/bash
set -ev
echo '>>> Now running shell script...'
npm i -g data-cli
data --version
data help
data info https://datahub.io/core/finance-vix

echo '>>> Install data-cli with yarn...'
npm uninstall -g data-cli
if [ $(uname) = 'Darwin' ]; then
  brew install yarn
else
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  sudo apt-get update && sudo apt-get install yarn
fi

export PATH="$(yarn global bin):$PATH"
yarn global add data-cli
data --version
data info https://datahub.io/core/finance-vix
```

**Comment by anuveyatsu** [comment]
FIXED - you can see builds on Travis or take a look at `.travis.yaml` and `test-script.sh` files:

- https://github.com/datahq/data-cli/blob/master/.travis.yml
- https://github.com/datahq/data-cli/blob/master/test-script.sh
