### ISSUE TITLE
New command line approach using "now-cli" semantics

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#28]
We decided to use the approach from https://github.com/zeit/now-cli so need to remove old code and reimplement basic commands.

## Acceptance criteria

* [x] skeleton as in "now-cli"
* [x] basic command "help" and tests for it

## Tasks

* [x] copy `/bin/now.js` and adopt it for our case (data.js)
* [x] create `/bin/data-help.js` for help command
* [x] tests
  * [x] start using ava
  * [x] tests for help command

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datopian/datahub-cli/pull/29
