### ISSUE TITLE
data push inlined dataset has an expected error message

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data-cli#284]
This issue reported here datahq/datahub-qa#24

When we try to publish inlined dataset, it throws the following error `> Error! [object Promise]`

## Acceptance criteria

* [x] Display a proper error message

## Tasks

* [x] Debug, why it is returning promise
* [x] Fix and add test

**Comment by Mikanebu** [comment]
FIXED, now if you try to push inlined dataset, you will get an error
```
> Error! Unfortunately, we do not support inlined datasets
```

**Comment by zelima** [comment]
@Mikanebu "Unfortunately"? that seems a bit strange to me :) Think without that would sound much better

**Comment by Mikanebu** [comment]
@zelima ```> Error! We do not support inlined datasets!```

**Comment by zelima** [comment]
@Mikanebu actually thinking more - that is not inlined dataset actually, but dataset with inline data so it should be:
`Error! We do not support dataset with inlined data`

**Comment by zelima** [comment]
@Mikanebu Also where can I review PR for this?

**Comment by Mikanebu** [comment]
@zelima DONE! See commit https://github.com/datahq/data-cli/commit/9b6a5b36bb1ceb42cb285fb5397f986f2bb437f1. PR for this https://github.com/datahq/data-cli/pull/285

**Comment by zelima** [comment]
@Mikanebu Ok, looks better I think
