### ISSUE TITLE
Automate QA tests for cat, info and validate commands

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#288]
As we've run QA tests several times manually, we want them to be automated so we don't spend time on running again.

## Acceptance criteria

* [x] QA tests for cat, info and validate commands are automated in the unit tests in this repo

## Tasks

* [x] cat command - https://github.com/datahq/data-cli/commit/ce333b9273b7b3cb66d11e90920ebd6f8170ea70
* [x] info command - https://github.com/datahq/data-cli/commit/00cde415921c1bfa3c3d0132dd163393e7c395e9
* [x] validate command - https://github.com/datahq/data-cli/commit/d402a571e91d8bc63039019899c3aa23e9d106a2

**Comment by anuveyatsu** [comment]
FIXED
