### ISSUE TITLE
[data cat] for  TSV files throws error

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data-cli#292]
Reported here datahq/datahub-qa#116

data cat does not work with TSV files, it throws the following error
```
> Error! We do not have a parser for that format: tsv
```

## Acceptance criteria

* [x] data cat is supported for `tsv` files

## Tasks

* [x] add tests in `data-cli`
* [x] refactor `data-cat.js` to support `tsv` files

**Comment by Mikanebu** [comment]
FIXED, now `data cat` for `tsv` remote/local files works fine. Please, see PR on data.js https://github.com/datahq/data.js/pull/35. And appropriate tests, see PR on `data-cli` https://github.com/datahq/data-cli/pull/293
