### ISSUE TITLE
Automate QA tests for "user rights & restrictions" section

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#297]
## Acceptance criteria

* [ ] All tests in QA tests for "user rights & restrictions" section are automated

## Tasks

* [x] create a new test modules "authorization.test.js" in `/test/` dir
* [x] automate the 8 test cases

**Comment by AcckiyGerman** [comment]
FIXED: we have tests for
- unauthorized user try to get private data
- authorized user try to get non-owner private data
