### ISSUE TITLE
Enable Travis CI for this repo

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#3]
We need continues integration to be sure nothing is failing on Each PR

## Acceptance criteria

* [x] Travis CI enabled and runs tests for each commit

## Tasks

* [x] create `travis.yml`
  *  https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
  * other node repos using travis: https://github.com/cybergreen-net/stats-new/blob/master/.travis.yml
* [x] configure repo setting and integrate with Travis 
* [x] add build status to README

**Comment by zelima** [comment]
FIXED. See status here https://travis-ci.org/datopian/datahub-cli
