### ISSUE TITLE
`data get {dhpkgid}` command using new approach

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#30]
Since we started using the approach from https://github.com/zeit/now-cli/ we want to reimplement our get command. There is also a number of changes in logic as the previous implementation did not meet our needs.

## Acceptance criteria

* [x] I can do `data get {dhpkgid}` and get the package
* [x] I can do `data help get` and see instructions on how to use `get`

## Tasks

* [x] implement `data help get` command
  * [x] tests
  * [x] have a nice manual as it is in now-cli
* [x] implement `data get {dhpkgid}` command
  * [x] tests
  * [x] checking config and default server
  * [x] checking if folder is empty
  * [x] getting metadata
  * [x] downloading and saving files
  * [x] time elapsed
  * [x] progress bar
  * [ ] spinner

## Analysis

```bash=
# get of whole package
# saves to relative subdirectory {publisher}/{package}
data get {dhpkgid}
```

Algorithm for `data get {dhpkgid}`

* [x] 0. check config and check valid dhpkgid ...
    * [x] 1. Config file exists: use server url form there
    * [x] 2. Not exist: use default one (or create config file with default values for user???)
* [x] 1. Look up data package via API
    * [x] 1. OK: get bitstore url and proceed
    * [x] 2. Not OK: report error and exit (e.g. 404) 
* [x] 2. Check if dest directory empty [dest directory = ${cwd}/{publisher}/{package}]
    * [x] 1. Empty: proceed
    * [x] 2. Not empty: ?? (warn, error, ignore??) 
    	 * [x] 1. error (Not empty) and exit  
* [x] 3. Download datapackage.json
* [x] 4. Download (in parallel if we can): README.md plus all resources
    * [x] Report time elapsed
    * [x] Report progress
    * [ ] Show spinner etc

**Comment by anuveyatsu** [comment]
FIXED in #31 and #32
