### ISSUE TITLE
[get] ability to get private datasets from DataHub

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#301]
As a Publisher, I want to be able to "get" my own private datasets from DataHub so I can edit it and re-push with my changes.

Original issue - https://github.com/datahq/datahub-qa/issues/128

## Acceptance criteria

* [x] as owner I can get my private datasets
* [x] other users cannot get my private datasets

## Tasks

* [x] analysis
* [x] refactor `/bin/data-get.js` module
* [x] create test case

## Analysis

If I run `data get https://datahub.io/test/private-cli-test`, I would get `Error! invalid json response body at https://api.datahub.io/source/...`. This is happening because:

1. we try to load `Dataset` object from given identifier (url)
2. when loading `Dataset` object it tries to load descriptor. For datahub URLs, it tries to fetch `https://datahub.io/test/private-cli-test/datapackage.json` which is private and returns 404 (unless token is setup)

How to fix it:

- Option 1: handle private datasets in `data.js` library
  - but `data.js` library is designed to be minimal and probably universal so it can be used from different projects, not just datahub specific...
- Option 2: handle private datasets in "get" module of `data-cli` library
  - this sounds reasonable because it's the only place where it's needed.

Recently, we've started downloading only "zipped" version of the dataset from datahub and then unzip it. The logic is:

1. we fetch a descriptor from datahub
2. find "zip" resource
3. fetch "zip" resource
4. unzip it
5. save to the disk

Instead of that, we could use frontend API for getting "zipped" resource so we don't need to fetch descriptor and we can pass user's "token" as params so we delegate handling private resources to the frontend API:

```
https://datahub.io/{owner}/{dataset}/r/{dataset}_zip.zip?jwt={token}
```

**Comment by anuveyatsu** [comment]
FIXED - Now "get" command works with private datasets:

When an identifier is datahub type, we don't load Dataset object but use frontend API for getting "zipped" version of a dataset. This way we delegate handling of private datasets to the frontend, where it's already implemented.
