### ISSUE TITLE
[push] Push excel sheet by name

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#304]
As a Publisher, I want to be able to push an Excel sheet by name so I don't need to count its sheet index, especially when my file has lots of sheets.

This initially described here - https://github.com/datahq/datahub-qa/issues/88

## Acceptance criteria

* [x] I can do following with Excel file that has 2 sheets: `data push myfile.xlsx --sheets=mySheetName`

## Tasks

* [x] refactor xlsx parser (data.js) to take either index or name (this is actually not required for this issue but is nice to have for future)
* [x] refactor logic for handling excel files in datahub-client lib

## Analysis

In datahub-client repo, we have following logic. Note we have `sheetNames` array available:

1. check if `sheets` option is provided (if it equals to `all` then we handle it differently)
2. split `sheets` option by `,` and map values by parsing it to integer
3. if after mapping value is false or `sheetNames.length < value` then throw error
4. infer schema from the sheet and pass the sheet index in tabulator configs

However, this logic doesn't consider the case when user passes a sheet name. We want to handle that case and convert sheet name to index so we're able to pass it in the tabulator configs:

1. same
2. split `sheets` option by `,`
3. map values: if parsing value to integer returns true then parse it, otherwise leave it
4. if value is number then check if it isn't out of range OR if value is string then check if it exists in the `sheetNames`. Throw error if not.
5. if value is string then identify its index in `sheetNames` and assign this value to be index
6. continue as before

**Comment by anuveyatsu** [comment]
FIXED and available in https://github.com/datahq/data-cli/releases/tag/v0.7.14
