### ISSUE TITLE
[validate] improve error message for invalid URLs

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#311]
Reported in https://github.com/datahq/datahub-qa/issues/142

## Acceptance criteria

* [x] I see clear message, eg, which resource caused the error and which path: `data validate https://github.com/frictionlessdata/test-data/tree/master/packages/invalid-remote-path`

## Tasks

* [x] refactor `validate` module in `datahub-client` so it throws actual errors + adds information about `resource`'s name and path
* [x] refactor `data-validate.js` module in `data-cli` so it prints more informative message

**Comment by anuveyatsu** [comment]
FIXED - requires `datahub-client@0.3.1`
