### ISSUE TITLE
[Delete] introduce data purge

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#317]
We need a new command for deleting data sets: 
```
data purge [idenfier]
```

## Acceptance Criteria

* [ ] before delete user is prompted with a message to force typing dataset name

## Tasks

* [ ] add `data purge` to bin
* [ ] Prompt user
* [ ] Help and docs
* [ ] tests?
