### ISSUE TITLE
[validate] commands need a spinner

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#319]
Reported in https://github.com/datahq/datahub-qa/issues/148

## Acceptance criteria

* [x] when I run `validate` command, it shows a spinner that gives me feeling of ongoing process
* [x] Bonus: along with spinner I can see details of what's happening, e.g., validating `resource-x`

## Tasks

* [x] analysis of where to implement
* [x] re-work on datahub-client
* [x] refactor data-cli 'validate' module

## Analysis

"Get" command already has a spinner.

### Datahub-client:

Currently, we have separate functions for validation which doesn't give us ability to track what's happening inside validation process. We need to do a re-work here so we use OOP approach and we extend `EventEmitter` class. This way we can emit events to the caller, e.g., we can tell which file is being validated etc.

### Data-cli:

Need to refactor according to changes in datahub-client library

**Comment by anuveyatsu** [comment]
FIXED and available from v0.8.4 - https://github.com/datahq/data-cli/releases/tag/v0.8.4
