### ISSUE TITLE
GA + Sentry integration

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#321]
1. As an Admin, I want to track CLI usage so I know what commands are mostly utilized by users.
  * so I have a report with total numbers of calls for each command, e.g., `push: 201`, `get: 333`, `login: 250`...
2. As an Admin, I want to track behaviour of publishers so we can improve our app.
  * so I have a session flow such as: `data -v` => `data validate path` => `data push path` => `data login` => `data push path` => `data info path`
* ~~As an Admin, I want to know how many times publishers init "push" command so I can understand what part of it has failed.~~
3. As an Admin, I want to monitor every error/exception/crash so I can identify bugs of the app and work on it.
  * so I have a report with error message + time happened + version used
    *  and then I can see aggregated data, e.g., how many times occurred a certain error

## Acceptance criteria

* [x] user stories above are satisfied

## Tasks

* [x] analysis
* [x] implement tracking basic usage stats
* [x] implement tracking user behaviour by sessions
* [x] implement monitoring errors/exceptions/crashes

## Analysis

**Question:** do we need a separate entity in GA? So stats are not mixed with website analytics.

**Answer:** we want to have single entity so we can track users behaviour in the different platforms by utilizing custom user-ids: https://support.google.com/analytics/answer/3123662?hl=en

GA analytics wrapper library for nodejs apps: https://github.com/peaksandpies/universal-analytics

### 1st user story: track basic usage

Using `Universal Analytics` we can have a tracker (event tracking) in `/bin/data.js` module:

Event category => command
Event action => first argument
Event label => all other arguments

```javascript=
const ua = require('universal-analytics')

const visitor = ua('UA-XXXX-XX')

visitor.event(command, args[0], args.slice(1, args.length - 1)).send()
```

It should be done somewhere here - https://github.com/datahq/data-cli/blob/master/bin/data.js#L98

### 2nd user story: track by session

By default, a Visitor instance is created and a random UUID is generated so we can automatically track a specific user. If necessary, we still can have custom UUID:

```javascript=
const visitor = ua('UA-XXXX-XX', 'datahub-user-id', {strictCidFormat: false})
```

### 3rd user story: monitor errors

Consider Sentry - why? Because we need to know what errors users are facing - probably most of users try to push but encounter some error that we're not aware of. Thus, we want to monitor each error occurred during the usage of data the CLI tool.

Here we're handling all uncaught exceptions and unhandled rejections - https://github.com/datahq/data-cli/blob/master/bin/data.js#L17-L24 so we can listen from here. While reporting errors, we want to know:
* which version of the CLI is running
* nodejs version - but what if this app wasn't installed via NPM so user's nodejs version doesn't play a role?
  * here is the way of identifying if it was installed via NPM - https://github.com/zeit/now-desktop/blob/c3b2dc504dd041e77f43fe6bd1b6bd0254c5c7f0/main/utils/binary.js#L165-L190
* if logged in - userid
* what command caused the error and what was the args, e.g., `push` and `<path>`

```javascript=
const {version} = require('../package.json')
const {config} =   require('datahub-client')

const Raven = require('raven')
Raven.config('your dsn').install()

const nodejs = installedWithNPM ? process.version : 'bin'

Raven.setContext({
  version,
  nodejs,
  userid: config.get('profile') ? config.get('profile').id : config.get('id'),
  args: process.argv
})

process.on('uncaughtException', (err) => {
  Raven.captureException(err)
  handleError(err)
})

process.on('unhandledRejection', (err) => {
  Raven.captureException(err)
  handleError(err)
})
```

and then we can capture other exceptions from the commands, e.g., `push` ...

**Comment by anuveyatsu** [comment]
FIXED and live on GA and Sentry.
