### ISSUE TITLE
Track if it's the first time the app is run

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#322]
We want to track first runs of the CLI app so we know how many new users start using it.

## Acceptance criteria

* [x] In GA, we track first runs of the app

## Tasks

* [x] install https://github.com/sindresorhus/first-run
* [x] on first run of the app, in `/bin/data.js` track event with: `category: cli`, `action: first-run`

**Comment by anuveyatsu** [comment]
FIXED and tracked starting from v0.8.9
