### ISSUE TITLE
data get does not work with DataHub's /r/ links

### ISSUE THREAD

**Issue by Mikanebu** [datopian/data-cli#323]
This issue reported here https://github.com/datahq/datahub-qa/issues/179
We want to save file with r links from DataHub

## Acceptance criteria

* [x] data get DataHub's /r/ links works fine

## Tasks

* [x] refactor `bin/data-get.js`
* [x] add test to QA spreadsheet
* [x] add test in `tests`

**Comment by Mikanebu** [comment]
FIXED, now we can get r links from DataHub
