### ISSUE TITLE
[push][push-flow] support for `--public` and `--publish` keywords

### ISSUE THREAD

**Issue by AcckiyGerman** [datopian/data-cli#326]
Original: https://github.com/datahq/datahub-qa/issues/193

## tasks

- [x] add tests
- [x] implement new keywords
- [x] update the help & docs

## Acceptance criteria

- [x] `--public` and `--publish` arguments leads to `findability: "published"` in the descriptor

**Comment by AcckiyGerman** [comment]
FIXED:
* `--public`, `--published`, `--publish` arguments lead to `"findability": "published"` in the descriptor
* Docs updated (with the --public keyword)
* test added for `--public`
* `push-flow` now checks that findability is correct (fixed in `datahub-client`)
