### ISSUE TITLE
Improve sentry reports: behaviour and content

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#329]
We have been tracking errors that users experience by sending reports to Sentry. By looking at collected reports, we can see that there are some things that can be improved:

* some CLI arguments are missing - probably due to the difference in the OS
  * solution: just send all arguments in the single property
* several reports are sent within a process - this is because a process doesn't exit until we receive a callback from Sentry
  * solution: promisify sending reports to Sentry

## Acceptance criteria

* [x] reports in Sentry dashboard include all CLI arguments
* [x] one report per process

## Tasks

* [x] refactor `/lib/utils/error.js` module to promisify report sending code
* [x] refactor modules in `/bin/` to work with it
* [x] include all arguments within a report

**Comment by anuveyatsu** [comment]
FIXED
