### ISSUE TITLE
[init] rewrite module in an OOP way extending EventEmitter class

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#335]
so it is reusable + we can listen for events from a single place + easy to add new events.

## Acceptance criteria

* [x] there is a class `Init` that has all necessary for init methods
* [x] all console logs are emitted via `message` channel

## Tasks

* [x] create a new `Init` class
* [x] add all necessary functions as methods to it
* [x] constructor should set interactive mode

**Comment by anuveyatsu** [comment]
FIXED and available in v0.9.0
