### ISSUE TITLE
[init] implement interactive vs default modes

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#336]
## Acceptance criteria

* [x] I can do `data init -i` which triggers dataset initializer in an interactive mode
* [x] I can do `data init` which triggers dataset initializer without interactivity - just goes through all files and dirs and generates descriptor
* [x] sets default license
* [x] if README exists sets content to `descriptor` property (first 100 chars)

## Tasks

* [x] make init non-interactive by default and add option --interactive or -i for interactive mode
  * [x] guess name from directory name
  * [x] use name to generate title
  * [x] set license to ODC attribution or PDDL (?)
  * [x] (?) Use readme to set description

**Comment by zelima** [comment]
FIXED
