### ISSUE TITLE
[push][validate][info] commands don't work with path to datapackage.json

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#337]
As reported in https://github.com/datahq/datahub-qa/issues/208

## Acceptance criteria

* [x] these work:
  * [x] `data validate datapackage.json`
  * [x] `data info datapackage.json`
  * [x] `data push datapackage.json`

## Tasks

* [x] in `data.js` library create tests for `parseDatasetIdentifier` function for this case
* [x] fix the function
* [x] publish `data.js@0.11.2`
* [x] release the CLI using this version of data.js

**Comment by anuveyatsu** [comment]
FIXED in v0.9.1
