### ISSUE TITLE
[push][validate] commands with no arguments on WinOS

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#338]
As reported in https://github.com/datahq/datahub-qa/issues/207

## Acceptance criteria

* [x] I can run `push` and `validate` commands with no arguments and it'll be applied to cwd

## Tasks

* [x] in `data.js` library, refactor `parseDatasetIdentifier` function
* [x] publish new version of `data.js` in npm
* [x] release a new CLI with the fix

**Comment by anuveyatsu** [comment]
FIXED in v0.9.2
