### ISSUE TITLE
[init] command doesn't get correct name of the cwd on WinOS

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#339]
As reported in https://github.com/datahq/datahub-qa/issues/206

## Acceptance criteria

* [x] when I run `data init` on Windows, `name` and `title` properties are set correctly using name of CWD

## Tasks

* [x] refactor `datahub-client` library's `init` module - use `path.basename` to get name of cwd
* [x] publish new version of `datahub-client` on NPM
* [x] release a new CLI version

**Comment by anuveyatsu** [comment]
FIXED in v0.9.2
