### ISSUE TITLE
[Windows] backslash vs forwardslash problem

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#340]
As reported in https://github.com/datahq/datahub-qa/issues/223 we want to make sure that paths are generated correctly.

Also, we want to verify there are no such issues with other commands in the CLI.

## Acceptance criteria

* [x] init command works correctly
* [x] no such problems with other commands

## Tasks

* [x] reproduce the problem on Windows
* [x] debug, identify the source
* [x] implement the fix
* [x] test out all other commands for possible situations

**Comment by anuveyatsu** [comment]
FIXED and will be available with the next release of the CLI
