### ISSUE TITLE
[Windows] copying to clipboard is not working

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#341]
As reported in https://github.com/datahq/datahub-qa/issues/112, copying to clipboard is not functional on Windows OS.

## Acceptance criteria

* [x] after a successful push, the CLI copies the URL to the clipboard on the Windows OS

## Tasks

* [x] debug and identify the source of the problem
* [x] analyse possible solutions
* [x] implement the fix

**Comment by anuveyatsu** [comment]
FIXED and will be available with the next release of the CLI
