### ISSUE TITLE
Can't complete the login process with Chrome (Linux)

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#346]
Originally coming from here https://github.com/datahq/datahub-qa/issues/236

As a user, I want to be able to complete my sign-up/log-in process with any browser, so that I can start using datahub tools  

## Acceptance Criteria

* [x] Able to login from chrome 

## Tasks

* [x] Do the analysis 
* [x] Come up with Solution
* [x] refacto data-cli to accept `-i` or `--interactive` flag and display url if True

## Analysis

Doing a bit of analysis it seems this is a problem related either to browser or OS. Also see the discussion here https://github.com/sindresorhus/opn/issues/83 (we are using opn for opening urls in brawser)

As a solution, we will make it available to display URL if needed and  notify users that if they encounter the similar problem they can display URL and paste in browser

**Comment by zelima** [comment]
FIXED
