### ISSUE TITLE
Normalize datapackage.json

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#37]
We want command line to normalise datapackage.json according to the FD specs. The script will fix some common issues like unsupported types, formats, schemas.

```
# command to normalize a data package
# upgrade from pre-v1.rc1 or rc2

data dp norm[alize] [path to directory or datapackage.json]
```

### Acceptance Criteria

* [x] I can run `data dp norm[alize]` and get my datapackage.json normalized

### Tasks

* [x] Specify how the function will operate e.g. what will it correct, will it ever error, will you run validate beforehand (partially or o/w)?
  * it will correct:
    * dp name
    * resource names
    * resource field types (e.g., replace float, decimal etc with `number`)
    * resourse date formats (e.g., make format `any`)
    * dp metadata structure (e.g., converts `sources` from object to array of objects)
  * it errors if path is invalid or there are no datapackage.json
  * it is recomended to run normalize begore validation command
* [x] Create function to normalize datapackage.json
  * [x] migrate from python script
  * [x] bin file to execute commands
* [x] Create tests

### Analysis

* [x] Read FD specs
* [x] Look into spreadsheet for the common errors in broken Data Packages
https://docs.google.com/spreadsheets/d/14kJluhePaMOx6vYBic0poVjDYK3I8-v_xF3sv4Focac/edit#gid=0
Checking new version of FD specs and preparing normalization script ...
* [x] Read alternative written python code in DPM-PY(`modify.py`)

**Comment by anuveyatsu** [comment]
FIXED in #41

**Comment by anuveyatsu** [comment]
REFACTORED AND FIXED in #54
