### ISSUE TITLE
data purge command

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#38]
We want to be able to delete data package from the server.

## Acceptance criteria

* [x] I can purge a data package by running `data [-f] purge`
* [x] warn user before purging - let him/her to type package name if [-f] option is given

## Tasks

* [x] analyse `dpm-py` purge command
* [x] write tests
* [x] implement referencing `dpm-py`
  * [x] handle [-f] option

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datopian/datahub-cli/pull/40

**Comment by anuveyatsu** [comment]
There is bug when using without `-f` option - after confirming with package name it does nothing.

**Comment by anuveyatsu** [comment]
FIXED in #57
