### ISSUE TITLE
Installation and usage instruction 

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#4]
We need instructions on how to install and use datahub-cli. We want to follow Document Driven Development approach.

## Acceptance Criteria

- [x] clear and simple instructions for installing and usage
- [x] clear instrcutions for developers

## Tasks 

- [x] usage section
  - [x] installation
    - [x] as pkg
  - [x] getting help message
- [x] for developers section
  - [x] installation
  - [x] tests

**Comment by rufuspollock** [comment]
@zelima ultimately we will want a binary style install like zeit-cli but for now we can use npm 😄

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datopian/datahub-cli/commit/780cd502eed139cadda0b6dda8e6567a4d9cd17a
