### ISSUE TITLE
Generic error/logger handler

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#42]
We have many places in lib or bin where we need to log appropriate messages. Currently, we are using `console.log()` or `console.error()` and doing the coloring each time. Will be nice if we have a generic function that takes error type and message and logs appropriately with nice colors.

## Acceptance criteria

* [x] No more in-lined error handling in the code
* [x] Generic function inside utils that handles logs

## Tasks

- [x] write tests
- [x] write fucntion that hangle logs

## Analysis

Function would take 

```
const logger = (logType, message='') => {
  switch (logType) {
    case 'error':
      let mesage = do coloring and formatting
      console.error(message)
      break;
    case 'warning':
      let mesage = do coloring and formatting
      console.error(message)
      break
    etc ....
  }
}
```

**Comment by zelima** [comment]
FIXED in #44
