### ISSUE TITLE
Move commonly used functions in utils

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#45]
We have functions for checking if dp exists, reading dp, logging messages etc.. that are used in many different places. Would be better if we moved them into one place and used from there. 

## Acceptance criteria

- [x] We do not have same exact functions written in different places
- [x] functions are tested

## Tasks

- [x] move out all the common functions in utils/common
- [x] create new ones if needed Eg Identifier parser function
- [x] refactor code to use that functions

**Comment by anuveyatsu** [comment]
FIXED in #46
