### ISSUE TITLE
Spinner [and reusable progress bar]

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#48]
We want to have a nice spinner that appears when making API calls or on any other processes that take a noticeable amount of time. We also want our existing progress bar to be reusable if possible.

## Acceptance criteria

* [ ] a nice spinner and progress bar on `get` and `info` commands

## Tasks

- [x] get familiar spinner and progress bar libraries and play around.
- [x] register spinner and progress bar in utils
- [x] use them in functions 
- [ ] workaround to use prgressbar for each stream

**Comment by rufuspollock** [comment]
FIXED. Largely fixed. Issue re progress bar needs to be looked at again - and separately (main priority is push not get anyway).
