### ISSUE TITLE
Convert all help outputs to use markdown

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#49]
We want to write our help messages in markdown. For printing it to the terminal use `customMarked` function from `/lib/utils/marked.js`.

## Acceptance criteria

* [x] all help messages are written in markdown

## Tasks

* [x] rewrite all help messages in markdown
* [x] import to appropriate modules in `/bin/`
* [x] test it is outputting correct messages
* [x] read through and update help messages according to current status (or even future status)

## Analysis
Create folder `/docs/` with markdown files  and import to appropriate /bin/{command}.js
For each help message, we can create markdown file. For example, `data-dp-normalize.md` which will contain help message for `data-dp-normalize` command. 
Pros:
Less code in /bin folder.
Easy to manage and write
Further use in docs

**Comment by anuveyatsu** [comment]
FIXED in #55
