### ISSUE TITLE
datahub get command

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#5]
Command for getting data from datahub 

Proposal: 
```
# by default simply outputs to stdout
datahub get {publisher}/{dataset}/{name}[.extension]

# (can also download to current directory (or even to stdin)
datahub get {publisher}/{dataset}/{name}[.extension] {dir or path}
```

## Acceptance Criteria

* [x] No config is needed
* [x] Command `datahub get {publisher}/{dataset}/{name}[.extension]` outputs data in stdout
* [x] Command `datahub get {publisher}/{dataset}/{name}[.extension] .` writes data into `{name}[.extention]`
* [x] In case data not found outputs `404 - Data Not Found` in stdout
* [x] In case of error outputs error message in stdout
* [x] In case wrong arguments outputs help message (`datahub --help`)

## Tasks 

* [x] do analysis [1]
* [x] create fixtures with some sample data Eg: `test/fixtures/sample.csv` [1]
* [x] create failing tests for `get()` function, for all possible cases [2]
* [x] modify `get()` function in `/lib/index.js` to pass the tests [2]
* [x] document new instructions in README.md [1]

## Analysis

* should we output whole data in stdout? 
  * maybe optional argument `-l` `--limit` - displays N rows of the file (default 100?)

**Comment by zelima** [comment]
FIXED. for now `datahub get` command is working fine, maybe not flawlessly, but working. for further development we can reopen or open a new issue
