### ISSUE TITLE
Identifier parser function

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#59]
Many commands will require support for multiple different sources e.g. local file path, data package identifier or datahub identifier. We would like to have a very robust common function for doing this parsing with as much of this upstream in the `datapackage-identifier-js` library.

https://github.com/frictionlessdata/datapackage-identifier-js

```
parseIdentifier('...')

{
  name:
  owner:
  # no trailing slash (url in old spec becomes path)
  path: url or file path to base of dp
  dataPackageJsonPath: url or file path to ....
  type: url | local | datahub | github 
  original: ... 
  version: ...
  resourcePath: ... 
}
```

## Acceptance criteria

* [x] `parsePackageIdentifier(string, type=null)` method that reuses upstream library

## Tasks

* [x] analysis
* [x] refactor `parseIdentifier` function in `/utils/common.js`
* [x] refactor `get.js` and `info.js`
* [x] refactor tests

## Analysis

// OLD
We can create a new function for handling {dhpkgid}, e.g., in `/index.js` we can have `parseDhPkgId(dhId)` function:

```javascript
exports.parseDhPkgId = function (dhId) {
  var out = {
    name: '',
    publisher: '',
    path: '',
    type: ''
  }

  // remove `/` in the beginning and in the end
  var dhIdArray = dhId.split('/')
  dhId[0] === '/' ? dhIdArray.shift() : void(0)
  dhId[dhId.length - 1] === '/' ? dhIdArray.pop() : void(0)
  
  // get publisher, name and path
  [out.publisher, out.name] = dhIdArray
  out.path = dhIdArray.slice(2).join('/')

  return out
}
```

Why do we need `type`?

**Comment by anuveyatsu** [comment]
FIXED in #62
