### ISSUE TITLE
datahub push command

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#6]
Command for publishing files on Datahub

Simplest option:

```
# Push a data package (datapackage.json in CWD)
data push
```

## Acceptance Criteria

- [x] Able to publish 
- [x] should output link to the published data package in the site
- [x] I can do `data push` and it works similar to `dpm publish` from `dpm-py`

## Tasks

* [x] refactor cli like now [1]
* [ ] generate dp.json - #10 (for now assume it's there)
* [x] descriptor validation - #14 
* [x] check/create local credentials - #12 
* [x] #19 
  * [x] load config function
  * [x] check dp exists function
  * [x] authentication
  * [x] collect file info
  * [x] authorize
* [x] upload to BitStore - #16 

## Analysis

0. Load config
	1. Check file exists
		1. OK: continue
		2. Not OK: ask to run `data config` and set up
	2. Check if config has all key-values pairs
		1. OK: continue
		2. Not OK: Tell what's missing, ask to run `data config` 
1. Check datapackage.json exists (~~and valid?~~)
   1. OK: continue
   2. Not OK: error and exit
2. (?) Validate (dp and resources)
   1. OK: continue
   2. Not OK: 
   	  1. error with clear message about what files invalid and exit
   	  2. warn it is invalid and ask if wants to proceed
   		  1. Yes: continue
   		  2. No: exit 
3. Authenticate on `/api/auth/token`
   1. OK: get token
   2. Not OK: error and exit
4. Collect information about files (descriptor, resources specified in descriptor and readme - **we going to push only these files**)
	 1. get hash
	 2. get files size
		  1. OK: continue
		  2. Not OK: 
4. Authorize `/api/datastore/authorize` - POST info from previous step + token
   1. OK: get presigned urls for upload
   2. Not OK: error and exit
5. Upload each file into BitStore (using urls from prev step) - here we can utilize async feature of JS
   1. OK: go to next step
   2. Not OK: error and exit
6. Finalize `/api/package/upload` - 
   1. OK: console log URL for published datapackage and exit
   2. Not OK: error and exit

### // OLD ANALYSIS
* To publish data we first need to have user regisetered as publisher on datahub. So at this point user should already have setup configuration (user, secret, server)
* what are we doing with "valid" packages that have valid datapackage.json? should simple `datahub push` act like current dpm publish?
* What should be the link to the scratchpad file? 

### Scratchpad

Probably each publisher would have a scratchpad data package (so it is like a data package with name as scratchpad) - `{publisher}/scratchpad`.

* [ ] `datahub push` command that pushes from stdin to scratchpad (no validation, no dp.json checking)

Q: Can we have data files without descriptor?

### Not Scratchpad

We can split this issue into smaller parts by looking at implementation in https://github.com/frictionlessdata/dpm-py/issues/1 :

#### Part 1 - generate datapackage.json

First, we need to check if there is already a `datapackage.json`. If not then we generate it:

* [ ] check if `dp.json` exists
* [ ] if yes, do nothing; if not then generate based on `csv, tsv, json, geojson, topojson etc.` files in current (and child) directories.

#### Part 2 - validation

For metadata implement stand alone validator from https://github.com/frictionlessdata/datapackage-js

Also take a look at https://github.com/frictionlessdata/dpm-py/blob/master/dpm/client/__init__.py for data validation using goodtables.

#### Part 3 - check local credentials

* [ ] config file as in dpm-py
* [ ] check credentials from it

#### Part 4 - authentication

Do authentication and get session token - http://docs.datapackaged.com/developers/authentication/

#### Part 5 - authorize on BitStore, upload files and finilize

http://docs.datapackaged.com/developers/api/

**Comment by anuveyatsu** [comment]
FIXED in #53 

- simple `data push` command is implemented
- `data push {file}` is not going to be part of this epic
