### ISSUE TITLE
Commands are working very slowly

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#60]
After we have added `babel` modules ( #51 ) our system became significantly slower, e.g., it takes 2-3 seconds to just run the help command. Probably it is because babel compiles ES6 to ES5 + `babel-polyfill` emulates full ES6 environment. 

What can we do?

* One solution would be to implement only required parts of `babel`, e.g. probably we don't need polyfill but can use some sort of transformation library as it is done in now-cli:
https://github.com/zeit/now-cli/blob/master/package.json#L71

## Acceptance criteria

* [x] running commands does not take noticeable amount of time (unless it is a HTTP request)

## Tasks

* [x] analysis what features of ES6 and beyond we are using [30m]
* [x] find appropriate compilers/transpilers [30m]
* [x] test out the speed [10m]
