### ISSUE TITLE
Config file should have "bitStoreUrl" property

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#61]
We want to have `bitStoreUrl` property in config file.

## Acceptance criteria

* [x] new property in config file
* [x] when I run `data config` it asks me for `bitStoreUrl`

## Tasks

* [x] refactor config.js
* [x] refactor tests

**Comment by anuveyatsu** [comment]
FIXED in #62
