### ISSUE TITLE
Refactor library to use parseIdentifier and datapackage lib

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#65]
* refactor commands to use parseIdentifier function
* refactor the library to use datapackage-js library for loading/creation
  * e.g., take a look at `data validate url`

```javascript=
  const identifier = utils.parseIdentifier(pkgId)
  let dp = await datapackage.DataPackage.load(identifier.pathPackageJsonUrl)
  // future
  // dp = await datapackage.DataPackage.load(identifier)
  // dp.descriptor.readme = ...
  // dp.descriptor.readmeSnippet = ...
  // dp.descriptor.readmePath = ...
  // utils.getReadme(dataPackage) - afterwards descriptor has README on it ...
```

## Acceptance criteria

* [x] I can run `data info https://github.com/...` and get info about data package in GitHub
* [x] I can run `data info data info http://someurl.com/path/to/datapackage/` and get info about data package in given remote path
* [x] I can run `data info publisher/name` and get info about data package in DataHub
* [x] All above points also apply for `data get` command
* [x] All above points also apply for `data validate` command
* [x] I can run `data info` and get info about data package in cwd
* [x] I can run `data validate` and get info about data package in cwd

## Tasks

* [x] refactor `parseIdentifier` function (see analysis for more details)
* [x] refactor `/lib/get.js`
* [x] refactor `/lib/info.js`
* [x] refactor `/lib/validate.js`
* [ ] ~refactor other modules to use `datapackage-js` library~

## Analysis

```
data info https://github.com/...
data info http://someurl.com/path/to/datapackage/
data info local/path
data info publisher/name

# problem last two are ambiguous!!
# solutions?

# A - introduce dh:// prefix for datahub stuff
data info dh://publisher/name

# B
# data info checks whether local path exists and uses that if present ...
# if local/path exists locally use that o/w try datahub
# Rufus: don't like B at all because of magic ...
data info local/path

# C
# disallow
data info local/path
# only allow doing in current directory ...
data info

---

# similar issues with data get, and validate command

# no issues with purge (dh only), push (not relevant)

# norm is local only

```

```
# only ambiguity is local path and datahub
parseIdentifier(identifier, hint='datahub') {
  out = dpident.parse('abc/xyz')
  // tidy up out to our form e.g. path for url etc
  ...
  
  if (out.local && hint=='datahub') {
    out.type = 'datahub'
    // reparse the identifier as datahub
  }
  
  return out
}
```

https://github.com/datopian/datahub-cli/issues/59

```
github
{
  name:
  owner: github user e.g. /rufuspollock/my-data
  # no trailing slash (url in old spec becomes path)
  path: url or file path to base of dp
  dataPackageJsonPath: url or file path to ....
  type: url | local | datahub | github 
  original: ... 
  version: ...
  resourcePath: ... 
}

# random url
{
  name: last part of path
  owner: null
  # no trailing slash (url in old spec becomes path)
  path: url or file path to base of dp
  dataPackageJsonPath: url or file path to ....
  type: url | local | datahub | github 
  original: ... 
  version: ...
  resourcePath: ... 
}
```

**Comment by anuveyatsu** [comment]
@rufuspollock 
`datapackage-js` library that we are using to instantiate a Datapackage object is not working with local path (`file:///Users/.../datahub-cli/datapackage.json`):
```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2):
Error: only absolute urls are supported
```

I suppose we should raise an issue about that on upstream repo and postpone supporting following features:

* when I run `$ data info` I can get information about a data package in cwd
* when I run `$ data validate` I can get a data package in cwd validated

**Comment by rufuspollock** [comment]
@anuveyatsu but is it working with a normal local path - i.e. not a file uri but `/Users/.../datahub-cli/datapackage.json`? Documentation explicitly says it supports local file paths: https://github.com/frictionlessdata/datapackage-js#datapackage

(BTW let's generally avoid file uris - where are these coming from?)

**Comment by anuveyatsu** [comment]
@rufuspollock it works with relative path, e.g., `dir/file.json`. However, it does not allow `/` in the beginning so `/Users/.../datahub-cli/datapackage.json` does not work:

```
Found illegal beginning character '/' in ...
```

Just tested with newer version (@1.0.0-alpha.4) and it does accept `/` in the beginning.

(BTW: File URIs are coming from `datapackage-identifier` lib.)

**Comment by rufuspollock** [comment]
@anuveyatsu for now we can live with relative urls. Up to you.

**Comment by anuveyatsu** [comment]
FIXED in #67  #70
