### ISSUE TITLE
"data push {file}" command

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#66]
*User stories*:

* *As a publisher I want to get my data published without additional work so I don't need to learn and spend my time.*

## Acceptance criteria:

* [x] `data push file` add files to scratchpad data package
  * [ ] [data package is private by default ...] --- not considered

## Tasks

* [x] refactor `data push` command to handle passing argument as a file path
* [x] reuse commands from init implementation
  * [x] refactor these commands if needed
* [x] work around spinner thing

## Analysis

`$ data push -h` will be updated with an options to pass a file path and with a description of what it does.

Rufus:
> Big question is whether i'm in a data package directory. If so then pushing a file from here should maybe have different semantics ...

> Simplest algorithm I can think of for files:

```
0. file path must be a child of current directory
1. check if remote datapackage.json (???)
    1. Yes: retrieve and add file and then push (in memory or temp directory)
    2. No: create datapackage.json and push it along with file 
```

**Comment by anuveyatsu** [comment]
FIXED in #79
