### ISSUE TITLE
data info command

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#7]
We want to have a command for getting Data Package info (preview). It should display info like on showcase page but on the command line (e.g. first paragraph of readme - then a list of files - then full readme).

Proposal:

```
$ data info {publisher}/{package}
```

## Acceptance Criteria

* [x] I can get information (with nice output) about a data package.

## Tasks

* [x] marked-terminal library - https://www.npmjs.com/package/marked-terminal
  * [x] install and ~setup custom styles~
* [x] setup `data.js` file for `info` command
* [x] `/bin/data-info.js`
  * [x] create tests
  * [x] setup skeleton
  * [x] write out help output
* [x] `/lib/info.js`
  * [x] create tests
  * [x] create function(s) that hits API and gets package info (readme, resources, etc.)

**Comment by anuveyatsu** [comment]
FIXED in #47
