### ISSUE TITLE
Build packaged binaries for installation

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#73]
As a User I just want a binary (no node, npm etc) so that I can move quickly

As a Developer I want to have binaries auto-built for each release so that I don't have to do this manually

## Acceptance criteria
* [x] we have a release including a built binary

## Tasks
* [x] Build the binary locally (so you know how it works)
* [x] Do research on how we can autobuild with github releases
  * See zeit - uses travis
  * Check out https://docs.travis-ci.com/user/deployment/releases/
  * Read about github releases
* [x] Experiment with creating github release manually
* [x] Configure travis to do build
* [x] Build a (test) release and check it works

*   pkg issue related to building binaries 
https://github.com/zeit/pkg/issues/144

**Comment by Mikanebu** [comment]
FIXED
