### ISSUE TITLE
Test out built packages

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#76]
We need to try out built packages on different platforms - MacOS, Linus and Windows (probably Windows is not mandatory atm)

## Acceptance criteria

* [x] As a Mac os user I can run datahub-cli without installing node.js
* [x] As a Linux user I can run datahub-cli without installing node.js

## Tasks

* [x] Uninstall node.js on Linux os user, and try to run and test it.
* [x] Uninstall node.js on Mac os user, and try to run and test it.

**Comment by Mikanebu** [comment]
Downloaded binaries from [releases](https://github.com/datopian/datahub-cli/releases) page. Tested for mac OS and linux OS. 
After downloading it needs to be in binary folder in order to run. 
Suggestion to link it with the following command:
`ln -s datahub-macos /usr/local/bin/data`. Otherwise, we have to run `datahub-macos` command instead of `data`
