### ISSUE TITLE
Autocompletion for CLI commands and auto-suggesting for mispellings

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#8]
We want to two extra features for our CLI commands:
* auto suggesting on mis-spelt commands
* Bash command line completions

## Acceptance Criteria

* [ ] if user types `datahub gte` it should output 
```
datahub: 'gte' is not a datahub command. See 'datahub --help'.

Did you mean this?
	get
```
* [ ] if user types `datahub ge` and hits tab it should autocomplete to `datahub get`

## Tasks

* [ ] research commander docs if it already provides any of them
* [ ] research if there already is Node libraries that will help
  * correct typo https://github.com/inca/did-you-mean

**Comment by anuveyatsu** [comment]
We haven't worked on that issue yet, but still a desirable option so keeping the issue open.
