### ISSUE TITLE
Prompt -> Inquirer.js

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data-cli#82]
At the moment, we are using `prompt` library for prompting a user. We want to start using `Inquirer.js` for more testability, maintainability (gets updated regularly), popularity (stars 1k vs 4k).

## Acceptance criteria

* [x] all CLI is now using `Inquirer.js` instead of `prompt`

## Tasks

* [x] refactor prompt function in `/lib/utils/prompt.js`
* [x] refactor `config.js`
* [x] refactor `init.js`
* [x] refactor `purge.js`
* [x] add tests

**Comment by anuveyatsu** [comment]
FIXED in #83
