### ISSUE TITLE
[epic] `data push FILE` done totally right

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#85]
Rework previous data push file effort #66 for new lib setup and approach.

```
data push PATH-to-FILE
```

## Acceptance criteria

* [x] results in a dataset on DataHub! (or at least entry in the relevant pipeline and rawstore)

## Tasks

* [x] Plan it out
  * [x] Work out how we create the "temporary" datapackage.json (do we just do it in memory)
    * we handle "temporary" datapackage.json in memory
* [x] Refactor code to do this

NTS

* Once i've pushed one file what happens if i want to add to that "dataset". Maybe I can't unless i explicitly get and add ... OR you could have `data add FILE DATASET`
  * Bit like gist on github ... 

## Analysis

We've moved to a totally "virtual" model for data packages as resources for pushing. But we could do a switch and use the on disk datapackage.json if it exists. This could have advantage that we preserve original dp.json perfectly:

```
// get Package itself (datapackage.json) as a Resource
let dpJsonResource = null
if ( pkg.path ) { 
  dpJsonResource = Resource.load('datapackage.json', {basePath: pkg.path})
} else { 
  // package is "virtual" if no path (i.e. exists in memory not coming
  // from a datapackage.json file)
  const _descriptor = lodash.cloneDeep(pkg.descriptor)
  // InlineResource
  dpJsonResource = Resource.load({
    path: 'datapackage.json',
    data: _descriptor
  })
} 
resources.push(dpJsonResource)
```

**Comment by zelima** [comment]
@anuveyatsu can you add estimate here?

**Comment by anuveyatsu** [comment]
FIXED - we have achieved pushing packages to `rawstore` and `specstore`, however, these services are not stable yet so time to time push command gets some errors. We can close that issue for now as its tasks were completed. We will open relevant issue in the future if we need to do refactoring according to changes in our backend services.
