### ISSUE TITLE
parsePath function

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#86]
parse a path to a data resource into a resource descriptor

## Acceptance criteria

* [x] returns a basic data resource (without a name)

```
path: myfile.csv
pathType: local | remote
name: myfile
format: (file extension if determinable)
mediaType: text/csv
encoding: 'utf-8'
```

## Tasks

* [x] path -> {path, pathType}
* [x] infer format / mediaType
* [x] infer encoding

## Analysis

```
const mime = require('mime-types')

class DataStream {
  constructor(path) {
    const mimetype = mime.lookup(path) || ''
    this.descriptor = {
      path: path,
      pathType: 'local',
      mediaType: mimetype,
      format: mimetype.split('/').pop()
    }
  }

  open() {

  }
}
```

**Comment by anuveyatsu** [comment]
FIXED in #89
