### ISSUE TITLE
getRawStream

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#87]
`getRawStream(descriptor)`

cf https://github.com/frictionlessdata/tableschema-js/blob/master/src/table.js#L217

## Acceptance criteria

* [x] method that returns readable stream from local path or remote url

## Tasks

* [x] create `DataStream` class with constructor that takes path and builds descriptor
* [x] create method `getRawStream` that returns readable stream (mostly copy paste from `tableschema-js` link provided above

**Comment by anuveyatsu** [comment]
FIXED in #91
