### ISSUE TITLE
cat (pipe/show) command for reading and writing a file

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#88]
Command to read/write (tabular) data in a variety of formats. Think of it like pandoc for data ...

```bash=
# default format is human readable ascii on stdout
# output formats: csv, markdown, ascii (excel)
# output: stdout (_) or file xyz.csv
data cat FILE [[FILE or stdout].FORMAT]

Examples:

data cat in.csv [stdout]
data cat in.xlsx out.csv
data cat in.csv out.md
```

Extended version would allow for data piping like old [datapipes][] e.g. doing operations on data via pipes:

```
# see datapipes syntax for ideas on this ...
data cat --pipe="grep abc | head" in.csv
# or ...
data cat abc.csv | data grep ... |
```

*For more on this see analysis below ...*

[datapipes]: https://github.com/okfn/datapipes

## User Stories

As a Data Wrangler I want to quickly inspect a CSV file so that I get a sense of what it looks like

* Want to see first only first XXX amount by default (but can configure this)

As a Data Wrangler I want to quickly view an Excel file so that I get a sense of what it looks like (so that ...)

* Get a list of the sheets in the excel (?)
* select sheet number

## Tasks

Dumpers:

* [x] csv -> txt (ascii) stdout
  * [x] refactor to txt dumper method/class in lib/cat.js - `const async dump_ascii(resource, outstream) {  ... }`
* [x] CSV dumper (trivial!)
* [x] Markdown dumper - https://github.com/wooorm/markdown-table
* [x] xls dumper (?)

Input file

* [ ] File types: this is handled by work on Resource object for now
* [ ] cli parses stdin and handles it (is this possible right now??)

Dumper and CLI supports:

* [x] stdout
* [x] file

## Analysis

See also

* http://okfnlabs.org/dataconverters/ - python library for converting different formats. Key insight was the API or returning (metadata, stream) (inspired by Apache Tika). This was improved further in tabulator-py
* https://github.com/okfn/datapipes

## Refactor

For @anuveyatsu 

The function ascii_dump should go to lib/cat.js

```
 argv.output_format // csv, ascii, xls, ...
  cat.dumpers[argv.output_format].dump(res, process.stdout)

  const ascii_dump(res, outstream) {
    const rows = await toArray(await res.rows)

    // process.stdout.columns not defined when piping so we assume 100
    const termwidth = process.stdout.columns || 100
    const numrows = rows[0].length
    // algorithm: termwidth - (1 each for each column edge + 1 extra)
    var eachColWidth = Math.floor(Math.max(5, (termwidth - numrows -1) / numrows))
    var colWidths = Array(numrows).fill(eachColWidth)

    let table = new Table({
        head: rows[0]
      , colWidths: colWidths
    })

    rows.slice(1).forEach(row => {
      table.push(row)
    })

    stream.pipe(table.toString())
  }
```

### OLD - Structure of stream based data

*Can use resource objects plus a packed model for streaming ...*

```
First line: datapackage.json
// blank (?)
streamed file data (object oriented json) or any other binary encoding
space
streamed file
```

**Comment by anuveyatsu** [comment]
FIXED. Available options:

* `data cat in.csv [stdout]`
* `data cat in.csv out.xlsx`
* `data cat in.csv out.md`
