### ISSUE TITLE
Coloring errors and output

### ISSUE THREAD

**Issue by zelima** [datopian/data-cli#9]
we need different colors for errors, warnings, output, progress bar

## Acceptance Criteria

* [x] commands output nice and readable messages

## Tasks

- [x] research library that does this for us
- [x] decide on colors
- [x] implement colouring/formatting on outputs

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/datopian/datahub-cli/commit/ca1895b3506d63d1e4302508f1e76d3855617b6e and https://github.com/datopian/datahub-cli/commit/854182c0ef36005f7a673c26f322927206187bbb
