### ISSUE TITLE
Refactor data push {package} for new API

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#92]
Refactor push of a full Data Package (different from push file which is #85)

## Acceptance criteria

* [x] data push package results in a package live on http://dh.io/{owner}/{name}
* [x] errors clearly and nicely reported

## Tasks

* [x] Do analysis
* [x] Prep
  * [x] Get rid of unnecessary config (e.g. secretToken)
* [x] Check we have token (otherwise request you login)
* [x] Get authorization for rawstore authorization
* [x] Get rawstore upload authorization `/rawstore/authorize` (most of this there but requires refactoring)
* [x] Do upload to object store
* [ ] Get the authorization for spec store
* [x] Create spec store sources using the sources API
* [x] Report to user the location online e.g. dh.io/core/finances-vix

Also needed:

* [x] better debugging
* [x] adding owner (user id - need in login first)

Extras:

* [ ] handling README - see also #106 

### Authentication

* We don't need to set secret token with config anymore. Jwt is set when user logs in `$ data login`.
  * So we need to get rid of prompting users for token during `$ data config` process
  * Instead of `getToken` method we need to `authenticate` method

API endpoint for authorize: `api.testing.datapackaged.com/rawstore/authorize`

**Comment by rufuspollock** [comment]
FIXED. Yay!
