### ISSUE TITLE
[epic] DataHub class to wrap DataHub related actions & API

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#98]
Want to centralize API interaction in one place (and possibly many of the actions).

## Tasks

For Push:

* [x] Stub a DataHub class
* [x] Choose the http lib we use (axios, request, node-fetch etc). ANS: node-fetch
* [x] Do push work - #92 
* [ ] ~~Do info work - #107~~ INVALID
* [ ] ~~Do get work - #108~~ - DEFERRED until we need it

**Comment by rufuspollock** [comment]
FIXED. We've done push, info does not really need DataHub interaction and get needs to wait until we are clear server side.
