### ISSUE TITLE
[epic] Data classes for working with data files and sets

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-cli#99]
## Acceptance criteria

All of the following work as expected:

* Package.load(/path/to/directory)
* Package.load(/path/to/datapackage.json)
* Package.load(url-directory)
* Package.load(url/datapackage.json)
* new Package(descriptor)

As expected means these attributes available ...:

* [x] descriptor
* [x] identifier
* [x] resources
* [x] README

Plus

* [ ] they work with basePath
* [ ] handle packages with mixed resource types (remote and local) (?)

All the following work as expected:

* Resource.load(path)
* Resource.load(url)
* Resource.load(array of data)
* new Resource(descriptor)

Plus:

* [x] work with basePath
* [x] work with csvl

## Tasks

* [x] Create Resource (Data/File) class
  * [x] #89 parsePath function to get basic info and path for a file
  * [x] #90 getObjectStream
  * [x] #91 getRawStream
  * [x] #104 Support for loading with local JSON data
  * [x] Remote url support
  * [x] basePath support
* [x] Create Package (Dataset) class
  * [x] Connect with Resource
  * [x] Load README

### Naming:

```
DataResource # don't like repetition of Data
Resource         # Possible but a bit generic
Data                 # Like the simplicity, would also fit with Dataset as the plural version
DataFile           # no because connotes only local
```

**Comment by anuveyatsu** [comment]
FIXED - we have working `Package` and `Resource` classes.

**Comment by rufuspollock** [comment]
@anuveyatsu can you make a summary of here what we are **not yet** testing out of the combinations listed above.

**Comment by anuveyatsu** [comment]
At the moment, we are missing tests (and probably implementations) for following scenarios:

* packages with mixed resource types (remote and local)
* packages in current working directory - need to figure out how we pass `cwd`

**Comment by rufuspollock** [comment]
@anuveyatsu let's fill out this spreadsheet together:

https://docs.google.com/spreadsheets/d/146LkK2Fo7iW1yHtkZ01-Om7AgvTfDwwNSJlLjbZxJFA/edit#gid=0
